/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { AddClosurePeriodCommand } from "../../models/addClosurePeriodCommand";

import type { ClosurePeriodListVM } from "../../models/closurePeriodListVM";

import { executeFetch } from "../../../mutator/executeFetch";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getListClosurePeriodsUrl = () => {
  return `/scheduling/v1/closure-periods`;
};

export const listClosurePeriods = async (options?: RequestInit): Promise<ClosurePeriodListVM[]> => {
  return executeFetch<ClosurePeriodListVM[]>(getListClosurePeriodsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListClosurePeriodsQueryKey = () => {
  return [`/scheduling/v1/closure-periods`] as const;
};

export const getListClosurePeriodsQueryOptions = <
  TData = Awaited<ReturnType<typeof listClosurePeriods>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listClosurePeriods>>, TError, TData>>;
  request?: SecondParameter<typeof executeFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListClosurePeriodsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listClosurePeriods>>> = ({ signal }) =>
    listClosurePeriods({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listClosurePeriods>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListClosurePeriodsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listClosurePeriods>>
>;
export type ListClosurePeriodsQueryError = unknown;

export function useListClosurePeriods<
  TData = Awaited<ReturnType<typeof listClosurePeriods>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listClosurePeriods>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listClosurePeriods>>,
          TError,
          Awaited<ReturnType<typeof listClosurePeriods>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListClosurePeriods<
  TData = Awaited<ReturnType<typeof listClosurePeriods>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listClosurePeriods>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listClosurePeriods>>,
          TError,
          Awaited<ReturnType<typeof listClosurePeriods>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListClosurePeriods<
  TData = Awaited<ReturnType<typeof listClosurePeriods>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listClosurePeriods>>, TError, TData>>;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useListClosurePeriods<
  TData = Awaited<ReturnType<typeof listClosurePeriods>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listClosurePeriods>>, TError, TData>>;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListClosurePeriodsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getAddClosurePeriodUrl = () => {
  return `/scheduling/v1/closure-periods`;
};

export const addClosurePeriod = async (
  addClosurePeriodCommand?: AddClosurePeriodCommand,
  options?: RequestInit,
): Promise<string> => {
  return executeFetch<string>(getAddClosurePeriodUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(addClosurePeriodCommand),
  });
};

export const getAddClosurePeriodMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addClosurePeriod>>,
    TError,
    { data?: AddClosurePeriodCommand },
    TContext
  >;
  request?: SecondParameter<typeof executeFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addClosurePeriod>>,
  TError,
  { data?: AddClosurePeriodCommand },
  TContext
> => {
  const mutationKey = ["addClosurePeriod"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addClosurePeriod>>,
    { data?: AddClosurePeriodCommand }
  > = (props) => {
    const { data } = props ?? {};

    return addClosurePeriod(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddClosurePeriodMutationResult = NonNullable<
  Awaited<ReturnType<typeof addClosurePeriod>>
>;
export type AddClosurePeriodMutationBody = AddClosurePeriodCommand | undefined;
export type AddClosurePeriodMutationError = unknown;

export const useAddClosurePeriod = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addClosurePeriod>>,
      TError,
      { data?: AddClosurePeriodCommand },
      TContext
    >;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof addClosurePeriod>>,
  TError,
  { data?: AddClosurePeriodCommand },
  TContext
> => {
  return useMutation(getAddClosurePeriodMutationOptions(options), queryClient);
};
export const getDeleteClosurePeriodUrl = (id: string) => {
  return `/scheduling/v1/closure-periods/${id}`;
};

export const deleteClosurePeriod = async (id: string, options?: RequestInit): Promise<void> => {
  return executeFetch<void>(getDeleteClosurePeriodUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteClosurePeriodMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteClosurePeriod>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof executeFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteClosurePeriod>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteClosurePeriod"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteClosurePeriod>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteClosurePeriod(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteClosurePeriodMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteClosurePeriod>>
>;

export type DeleteClosurePeriodMutationError = unknown;

export const useDeleteClosurePeriod = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteClosurePeriod>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteClosurePeriod>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteClosurePeriodMutationOptions(options), queryClient);
};
