apiVersion: v1
kind: Service
metadata:
  name: childmanagment-api
  labels:
    app: childmanagement-api
    release: production
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: childmanagement-api
    release: production
