/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */

export type AddAbsenceCommand = {
  childId?: string;
  startDate?: string;
  endDate?: string;
  /** @nullable */
  reason?: string | null;
};
