/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */

export type AddEndMarkCommand = {
  childId?: string;
  endDate?: string;
  /** @nullable */
  reason?: string | null;
};
