/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */
import type { DayOfWeek } from "./dayOfWeek";

export type AddScheduleCommandScheduleRule = {
  day?: DayOfWeek;
  timeSlotId?: string;
  groupId?: string;
};
