/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */
import type { AddScheduleCommandScheduleRule } from "./addScheduleCommandScheduleRule";

export type AddScheduleCommand = {
  childId?: string;
  startDate?: string;
  scheduleRules?: AddScheduleCommandScheduleRule[];
};
