/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */

export type AddTimeSlotCommand = {
  /** @nullable */
  name?: string | null;
  startTime?: string;
  endTime?: string;
};
