/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */

export type AddTimeSlotCommand = {
  name?: string;
  startTime?: string;
  endTime?: string;
};
