/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */
import type { BkrAgeRatio } from "./bkrAgeRatio";
import type { BkrRuleConstraint } from "./bkrRuleConstraint";

export type BkrAppliedRule = {
  minAge: number;
  maxAge: number;
  maxChildren: number;
  minProfessionals: number;
  constraints: BkrRuleConstraint[];
  ratios: BkrAgeRatio[];
};
