/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */

export type BkrAgeRatio = {
  age: number;
  maxChildrenPerProfessional: number;
};
