/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */
import type { BkrAppliedRule } from "./bkrAppliedRule";
import type { BkrProfessionalsBasis } from "./bkrProfessionalsBasis";

export type BkrCalculationSummary = {
  hasSolution: boolean;
  basis: BkrProfessionalsBasis;
  appliedRule?: null | BkrAppliedRule;
};
