/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */

export type BkrProfessionalsBasis =
  (typeof BkrProfessionalsBasis)[keyof typeof BkrProfessionalsBasis];

export const BkrProfessionalsBasis = {
  None: "None",
  GroupSizeMinimum: "GroupSizeMinimum",
  RatioCalculation: "RatioCalculation",
  OneChildLessSafeguard: "OneChildLessSafeguard",
} as const;
