/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */

export type ChildScheduleDailyVM = {
  scheduleId?: string;
  childId?: string;
  /** @nullable */
  timeSlotName?: string | null;
  startTime?: string;
  endTime?: string;
  /** @nullable */
  dateOfBirth?: string | null;
  /** @nullable */
  age?: number | null;
  isAbsent?: boolean;
  /** @nullable */
  absenceReason?: string | null;
};
