/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */
import type { DayOfWeek } from "./dayOfWeek";

export type ChildScheduleListVMScheduleRule = {
  day?: DayOfWeek;
  timeSlotId?: string;
  /** @nullable */
  timeSlotName?: string | null;
  startTime?: string;
  endTime?: string;
  groupId?: string;
  /** @nullable */
  groupName?: string | null;
};
