/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */
import type { DayOfWeek } from "./dayOfWeek";

export type ChildScheduleListVMScheduleRule = {
  day?: DayOfWeek;
  timeSlotId?: string;
  timeSlotName?: string;
  startTime?: string;
  endTime?: string;
  groupId?: string;
  groupName?: string;
};
