/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */

export type ClosurePeriod = {
  id?: string;
  tenantId?: string;
  startDate?: string;
  endDate?: string;
  /** @nullable */
  reason?: string | null;
};
