/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */
import type { GroupDailyOverviewVM } from "./groupDailyOverviewVM";

export type DailyOverviewVM = {
  date?: string;
  isClosed?: boolean;
  /** @nullable */
  closureReason?: string | null;
  groups?: GroupDailyOverviewVM[];
};
