/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */

export type GetGroupSummaryParams = {
  groupId?: string;
  date?: string;
};
