/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */
import type { ChildScheduleDailyVM } from "./childScheduleDailyVM";

export type GroupDailyOverviewVM = {
  groupId?: string;
  groupName?: string;
  schedules?: ChildScheduleDailyVM[];
};
