/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */
import type { TimeBlockSummary } from "./timeBlockSummary";

export type GroupSummaryVM = {
  groupId: string;
  groupName: string;
  date: string;
  timeBlocks: TimeBlockSummary[];
  requiredProfessionals?: number;
  numberOfChildren?: number;
};
