/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */
import type { PrintCellVM } from "./printCellVM";

export type PrintChildVMSchedule = Record<string, PrintCellVM>;
