/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */
import type { DayOfWeek } from "./dayOfWeek";
import type { PrintChildVM } from "./printChildVM";

export type PrintGroupWeekdayPageVM = {
  weekday?: DayOfWeek;
  /** @nullable */
  dates?: string[] | null;
  /** @nullable */
  children?: PrintChildVM[] | null;
};
