/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */
import type { DayOfWeek } from "./dayOfWeek";
import type { PrintChildVM } from "./printChildVM";

export type PrintGroupWeekdayPageVM = {
  weekday?: DayOfWeek;
  dates?: string[];
  children?: PrintChildVM[];
};
