/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */
import type { PrintChildVMSchedule } from "./printChildVMSchedule";

export type PrintChildVM = {
  id?: string;
  givenName?: string;
  familyName?: string;
  /** @nullable */
  dateOfBirth?: string | null;
  schedule?: PrintChildVMSchedule;
  index?: number;
  ageDisplay?: string;
  /** @nullable */
  name?: string | null;
};
