/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */
import type { PrintGroupVM } from "./printGroupVM";

export type PrintSchedulesVM = {
  month?: string;
  year?: number;
  groups?: PrintGroupVM[];
};
