/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */
import type { PrintGroupWeekdayPageVM } from "./printGroupWeekdayPageVM";

export type PrintGroupVM = {
  id?: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  pages?: PrintGroupWeekdayPageVM[] | null;
};
