/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */
import type { PrintCellVM } from "./printCellVM";

/**
 * @nullable
 */
export type PrintChildVMSchedule = Record<string, PrintCellVM> | null;
