/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */

export type PrintCellVM = {
  status?: string;
  /** @nullable */
  absenceType?: string | null;
  /** @nullable */
  startTime?: string | null;
  /** @nullable */
  endTime?: string | null;
};
