/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */

export type PrintCellVM = {
  /** @nullable */
  status?: string | null;
  /** @nullable */
  absenceType?: string | null;
  /** @nullable */
  startTime?: string | null;
  /** @nullable */
  endTime?: string | null;
};
