/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */
import type { PrintGroupWeekdayPageVM } from "./printGroupWeekdayPageVM";

export type PrintGroupVM = {
  id?: string;
  name?: string;
  pages?: PrintGroupWeekdayPageVM[];
};
