/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */

export type ScheduleByDateVM = {
  scheduleId?: string;
  childId?: string;
  /** @nullable */
  childFullName?: string | null;
  timeSlotId?: string;
  timeSlotName?: string;
  startTime?: string;
  endTime?: string;
  groupId?: string;
  /** @nullable */
  dateOfBirth?: string | null;
  age?: number;
};
