/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */

export type ScheduleByDateVM = {
  scheduleId?: string;
  childId?: string;
  /** @nullable */
  childFullName?: string | null;
  /** @nullable */
  timeSlotName?: string | null;
  startTime?: string;
  endTime?: string;
  groupId?: string;
  /** @nullable */
  dateOfBirth?: string | null;
  /** @nullable */
  age?: number | null;
};
