/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */
import type { AgeGroupSummary } from "./ageGroupSummary";
import type { BkrCalculationSummary } from "./bkrCalculationSummary";

export type TimeBlockSummary = {
  startTime: string;
  endTime: string;
  /** @nullable */
  timeSlotName: string | null;
  totalChildren: number;
  /** @nullable */
  requiredProfessionals?: number | null;
  /** @nullable */
  ageGroups: AgeGroupSummary[] | null;
  bkr: BkrCalculationSummary;
};
