/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */
import type { AgeGroupSummary } from "./ageGroupSummary";
import type { BkrCalculationSummary } from "./bkrCalculationSummary";

export type TimeBlockSummary = {
  startTime: string;
  endTime: string;
  timeSlotName: string;
  totalChildren: number;
  requiredProfessionals?: number;
  ageGroups: AgeGroupSummary[];
  bkr: BkrCalculationSummary;
};
