/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */
import type { ValidationError } from "./validationError";

export type UnprocessableEntityResponse = {
  status: number;
  errors: ValidationError[];
};
