/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */

export type UpdateEndMarkSettingsCommand = {
  isEnabled?: boolean;
  yearsAfterBirth?: number;
  /** @nullable */
  description?: string | null;
};
