/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */
import type { UpdateScheduleCommandScheduleRule } from "./updateScheduleCommandScheduleRule";

export type UpdateScheduleCommand = {
  startDate?: string;
  scheduleRules?: UpdateScheduleCommandScheduleRule[];
};
