/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */

export type ValidationError = {
  /** @minLength 1 */
  property: string;
  /** @minLength 1 */
  code: string;
  /** @minLength 1 */
  title: string;
};
