/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { useCallback } from "react";
import type { AddPersonCommand } from "../../models/addPersonCommand";
import type { GetAllPeopleParams } from "../../models/getAllPeopleParams";
import type { PersonListVM } from "../../models/personListVM";
import { useExecuteFetchPaginated } from "../../mutator/useExecuteFetchPaginated";
import { useExecuteFetch } from "../../mutator/useExecuteFetch";

export const useGetAllPeopleHook = () => {
  const getAllPeople = useExecuteFetchPaginated<PersonListVM[]>();

  return useCallback(
    (params?: GetAllPeopleParams, signal?: AbortSignal) => {
      return getAllPeople({ url: `/crm/v1/people`, method: "GET", params, signal });
    },
    [getAllPeople],
  );
};

export const getGetAllPeopleQueryKey = (params?: GetAllPeopleParams) => {
  return [`/crm/v1/people`, ...(params ? [params] : [])] as const;
};

export const useGetAllPeopleQueryOptions = <
  TData = Awaited<ReturnType<ReturnType<typeof useGetAllPeopleHook>>>,
  TError = unknown,
>(
  params?: GetAllPeopleParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAllPeopleHook>>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAllPeopleQueryKey(params);

  const getAllPeople = useGetAllPeopleHook();

  const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useGetAllPeopleHook>>>> = ({
    signal,
  }) => getAllPeople(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useGetAllPeopleHook>>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetAllPeopleQueryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useGetAllPeopleHook>>>
>;
export type GetAllPeopleQueryError = unknown;

export const useGetAllPeople = <
  TData = Awaited<ReturnType<ReturnType<typeof useGetAllPeopleHook>>>,
  TError = unknown,
>(
  params?: GetAllPeopleParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useGetAllPeopleHook>>>, TError, TData>
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = useGetAllPeopleQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const useAddPersonHook = () => {
  const addPerson = useExecuteFetch<string>();

  return useCallback(
    (addPersonCommand: AddPersonCommand) => {
      return addPerson({
        url: `/crm/v1/people`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: addPersonCommand,
      });
    },
    [addPerson],
  );
};

export const useAddPersonMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<ReturnType<typeof useAddPersonHook>>>,
    TError,
    { data: AddPersonCommand },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<ReturnType<typeof useAddPersonHook>>>,
  TError,
  { data: AddPersonCommand },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const addPerson = useAddPersonHook();

  const mutationFn: MutationFunction<
    Awaited<ReturnType<ReturnType<typeof useAddPersonHook>>>,
    { data: AddPersonCommand }
  > = (props) => {
    const { data } = props ?? {};

    return addPerson(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddPersonMutationResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useAddPersonHook>>>
>;
export type AddPersonMutationBody = AddPersonCommand;
export type AddPersonMutationError = unknown;

export const useAddPerson = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<ReturnType<typeof useAddPersonHook>>>,
    TError,
    { data: AddPersonCommand },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<ReturnType<typeof useAddPersonHook>>>,
  TError,
  { data: AddPersonCommand },
  TContext
> => {
  const mutationOptions = useAddPersonMutationOptions(options);

  return useMutation(mutationOptions);
};
