/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { AddPersonCommand } from "../../models/addPersonCommand";

import type { GetAllPeopleParams } from "../../models/getAllPeopleParams";

import type { PersonListVM } from "../../models/personListVM";

import { executeFetchPaginated } from "../../mutator/executeFetchPaginated";
import { executeFetch } from "../../mutator/executeFetch";

export const getAllPeople = (params?: GetAllPeopleParams, signal?: AbortSignal) => {
  return executeFetchPaginated<PersonListVM[]>({
    url: `/crm/v1/people`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetAllPeopleQueryKey = (params?: GetAllPeopleParams) => {
  return [`/crm/v1/people`, ...(params ? [params] : [])] as const;
};

export const getGetAllPeopleQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllPeople>>,
  TError = unknown,
>(
  params?: GetAllPeopleParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllPeople>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAllPeopleQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllPeople>>> = ({ signal }) =>
    getAllPeople(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllPeople>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllPeopleQueryResult = NonNullable<Awaited<ReturnType<typeof getAllPeople>>>;
export type GetAllPeopleQueryError = unknown;

export function useGetAllPeople<TData = Awaited<ReturnType<typeof getAllPeople>>, TError = unknown>(
  params: undefined | GetAllPeopleParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllPeople>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllPeople>>,
          TError,
          Awaited<ReturnType<typeof getAllPeople>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAllPeople<TData = Awaited<ReturnType<typeof getAllPeople>>, TError = unknown>(
  params?: GetAllPeopleParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllPeople>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllPeople>>,
          TError,
          Awaited<ReturnType<typeof getAllPeople>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAllPeople<TData = Awaited<ReturnType<typeof getAllPeople>>, TError = unknown>(
  params?: GetAllPeopleParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllPeople>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetAllPeople<TData = Awaited<ReturnType<typeof getAllPeople>>, TError = unknown>(
  params?: GetAllPeopleParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllPeople>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAllPeopleQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const addPerson = (addPersonCommand: AddPersonCommand, signal?: AbortSignal) => {
  return executeFetch<string>({
    url: `/crm/v1/people`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: addPersonCommand,
    signal,
  });
};

export const getAddPersonMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addPerson>>,
    TError,
    { data: AddPersonCommand },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addPerson>>,
  TError,
  { data: AddPersonCommand },
  TContext
> => {
  const mutationKey = ["addPerson"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addPerson>>,
    { data: AddPersonCommand }
  > = (props) => {
    const { data } = props ?? {};

    return addPerson(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddPersonMutationResult = NonNullable<Awaited<ReturnType<typeof addPerson>>>;
export type AddPersonMutationBody = AddPersonCommand;
export type AddPersonMutationError = unknown;

export const useAddPerson = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addPerson>>,
      TError,
      { data: AddPersonCommand },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof addPerson>>,
  TError,
  { data: AddPersonCommand },
  TContext
> => {
  const mutationOptions = getAddPersonMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
