apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduling-api
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0 
  selector:
    matchLabels:
      app: scheduling-api
  template:
    metadata:
      labels:
        app: scheduling-api
        release: production
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: kdvmanager-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: scheduling-pod
        image: ghcr.io/luuklabs/kdvmanager/scheduling.api:linux-main
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
        livenessProbe:
          httpGet:
            port: 8080
            path: /healthz
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            port: 8080
            path: /healthz
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          limits:
            memory: 200Mi
            cpu: 500m
          requests:
            memory: 10Mi
            cpu: 100m
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        env:
          - name: OTEL__ENDPOINT
            value: "http://otel-collector.observability.svc.cluster.local:4317"
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://otel-collector.observability.svc.cluster.local:4317"
          - name: OTEL_SERVICE_NAME
            value: "scheduling-api"
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
          - name: ASPNETCORE_URLS
            value: "http://0.0.0.0:8080"
          - name: POSTGRES_SERVER
            value: "private-db-kdvmanager-ams3-do-user-13194146-0.l.db.ondigitalocean.com"
          - name: POSTGRES_USER
            value: "doadmin"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kdvmanager-postgres-secret
                key: password
          - name: POSTGRES_PORT
            value: "25060"
          - name: POSTGRES_DATABASE
            value: "KDVManagerSchedulingDB"
          - name: ConnectionStrings__KDVManagerSchedulingConnectionString
            value: "Server=$(POSTGRES_SERVER); port=$(POSTGRES_PORT); database=$(POSTGRES_DATABASE); User ID=$(POSTGRES_USER); password=$(POSTGRES_PASSWORD); pooling=true; sslmode=require; Maximum Pool Size=5; Minimum Pool Size=1; Connection Idle Lifetime=300; Connection Pruning Interval=10"
          - name: RABBITMQ_DEFAULT_USER
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: RABBITMQ_DEFAULT_USER
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: RABBITMQ_DEFAULT_PASS
          - name: ConnectionStrings__RabbitMQ
            value: "amqp://$(RABBITMQ_DEFAULT_USER):$(RABBITMQ_DEFAULT_PASS)@rabbitmq.kdvmanager-prod.svc.cluster.local:5672/"
      initContainers:
      - name: scheduling-migration
        image: ghcr.io/luuklabs/kdvmanager/scheduling.migrator:linux-main
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
        env:
          - name: OTEL__ENDPOINT
            value: "http://otel-collector.observability.svc.cluster.local:4317"
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://otel-collector.observability.svc.cluster.local:4317"
          - name: OTEL_SERVICE_NAME
            value: "scheduling-migrator"
          - name: POSTGRES_SERVER
            value: "private-db-kdvmanager-ams3-do-user-13194146-0.l.db.ondigitalocean.com"
          - name: POSTGRES_USER
            value: "doadmin"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kdvmanager-postgres-secret
                key: password
          - name: POSTGRES_PORT
            value: "25060"
          - name: POSTGRES_DATABASE
            value: "KDVManagerSchedulingDB"
          - name: ConnectionStrings__KDVManagerSchedulingConnectionString
            value: "Server=$(POSTGRES_SERVER); port=$(POSTGRES_PORT); database=$(POSTGRES_DATABASE); User ID=$(POSTGRES_USER); password=$(POSTGRES_PASSWORD); pooling=true; sslmode=require; Maximum Pool Size=2; Minimum Pool Size=1; Connection Idle Lifetime=300; Connection Pruning Interval=10"