/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { AddGroupCommand } from "../../models/addGroupCommand";

import type { GroupListVM } from "../../models/groupListVM";

import type { ListGroupsParams } from "../../models/listGroupsParams";

import type { ProblemDetails } from "../../models/problemDetails";

import type { UnprocessableEntityResponse } from "../../models/unprocessableEntityResponse";

import { executeFetchPaginated } from "../../../mutator/executeFetchPaginated";
import { executeFetch } from "../../../mutator/executeFetch";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getListGroupsUrl = (params?: ListGroupsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/scheduling/v1/groups?${stringifiedParams}`
    : `/scheduling/v1/groups`;
};

export const listGroups = async (
  params?: ListGroupsParams,
  options?: RequestInit,
): Promise<GroupListVM[]> => {
  return executeFetchPaginated<GroupListVM[]>(getListGroupsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListGroupsQueryKey = (params?: ListGroupsParams) => {
  return [`/scheduling/v1/groups`, ...(params ? [params] : [])] as const;
};

export const getListGroupsQueryOptions = <
  TData = Awaited<ReturnType<typeof listGroups>>,
  TError = unknown,
>(
  params?: ListGroupsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listGroups>>, TError, TData>>;
    request?: SecondParameter<typeof executeFetchPaginated>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListGroupsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listGroups>>> = ({ signal }) =>
    listGroups(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listGroups>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListGroupsQueryResult = NonNullable<Awaited<ReturnType<typeof listGroups>>>;
export type ListGroupsQueryError = unknown;

export function useListGroups<TData = Awaited<ReturnType<typeof listGroups>>, TError = unknown>(
  params: undefined | ListGroupsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listGroups>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listGroups>>,
          TError,
          Awaited<ReturnType<typeof listGroups>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof executeFetchPaginated>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListGroups<TData = Awaited<ReturnType<typeof listGroups>>, TError = unknown>(
  params?: ListGroupsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listGroups>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listGroups>>,
          TError,
          Awaited<ReturnType<typeof listGroups>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof executeFetchPaginated>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListGroups<TData = Awaited<ReturnType<typeof listGroups>>, TError = unknown>(
  params?: ListGroupsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listGroups>>, TError, TData>>;
    request?: SecondParameter<typeof executeFetchPaginated>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useListGroups<TData = Awaited<ReturnType<typeof listGroups>>, TError = unknown>(
  params?: ListGroupsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listGroups>>, TError, TData>>;
    request?: SecondParameter<typeof executeFetchPaginated>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListGroupsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getAddGroupUrl = () => {
  return `/scheduling/v1/groups`;
};

export const addGroup = async (
  addGroupCommand?: AddGroupCommand,
  options?: RequestInit,
): Promise<string> => {
  return executeFetch<string>(getAddGroupUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(addGroupCommand),
  });
};

export const getAddGroupMutationOptions = <
  TError = UnprocessableEntityResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addGroup>>,
    TError,
    { data?: AddGroupCommand },
    TContext
  >;
  request?: SecondParameter<typeof executeFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addGroup>>,
  TError,
  { data?: AddGroupCommand },
  TContext
> => {
  const mutationKey = ["addGroup"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addGroup>>,
    { data?: AddGroupCommand }
  > = (props) => {
    const { data } = props ?? {};

    return addGroup(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddGroupMutationResult = NonNullable<Awaited<ReturnType<typeof addGroup>>>;
export type AddGroupMutationBody = AddGroupCommand | undefined;
export type AddGroupMutationError = UnprocessableEntityResponse;

export const useAddGroup = <TError = UnprocessableEntityResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addGroup>>,
      TError,
      { data?: AddGroupCommand },
      TContext
    >;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof addGroup>>,
  TError,
  { data?: AddGroupCommand },
  TContext
> => {
  return useMutation(getAddGroupMutationOptions(options), queryClient);
};
export const getDeleteGroupUrl = (id: string) => {
  return `/scheduling/v1/groups/${id}`;
};

export const deleteGroup = async (id: string, options?: RequestInit): Promise<void> => {
  return executeFetch<void>(getDeleteGroupUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteGroupMutationOptions = <
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteGroup>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof executeFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteGroup>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteGroup"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteGroup>>, { id: string }> = (
    props,
  ) => {
    const { id } = props ?? {};

    return deleteGroup(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteGroupMutationResult = NonNullable<Awaited<ReturnType<typeof deleteGroup>>>;

export type DeleteGroupMutationError = ProblemDetails;

export const useDeleteGroup = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteGroup>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof deleteGroup>>, TError, { id: string }, TContext> => {
  return useMutation(getDeleteGroupMutationOptions(options), queryClient);
};
