import { executeFetch } from "../mutator/executeFetch";

/**
 * Trial subscription status for the current tenant, returned by the
 * TenantManagement API (`GET /tenantmanagement/v1/trial-status`). Hand-written
 * (not generated by orval) because the endpoint backs cross-cutting trial
 * enforcement rather than a feature resource.
 */
export type TrialStatus = {
  trialStartDate: string;
  trialEndDate: string;
  daysRemaining: number;
  isExpired: boolean;
};

export const trialStatusQueryKey = ["trial-status"] as const;

export const getTrialStatusUrl = () => `/tenantmanagement/v1/trial-status`;

export const getTrialStatus = (options?: RequestInit): Promise<TrialStatus> =>
  executeFetch<TrialStatus>(getTrialStatusUrl(), { ...options, method: "GET" });
