apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- service.yml

labels:
- pairs:
    app: tenantmanagement-api
    component: api
    service: tenantmanagement

images:
- name: ghcr.io/luuklabs/kdvmanager/tenantmanagement.api
  newName: ghcr.io/luuklabs/kdvmanager/tenantmanagement.api
  newTag: linux-main
- name: ghcr.io/luuklabs/kdvmanager/tenantmanagement.migrator
  newName: ghcr.io/luuklabs/kdvmanager/tenantmanagement.migrator
  newTag: linux-main
