using KDVManager.Services.TenantManagement.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace KDVManager.Services.TenantManagement.Infrastructure.Configurations;

public class TenantConfiguration : IEntityTypeConfiguration<Tenant>
{
    public void Configure(EntityTypeBuilder<Tenant> builder)
    {
        builder.ToTable("Tenants");

        builder.HasKey(t => t.Id);

        // Id is minted by the application at provisioning; never generated by the store.
        builder.Property(t => t.Id)
            .ValueGeneratedNever();

        builder.Property(t => t.Name)
            .IsRequired()
            .HasMaxLength(200);

        builder.Property(t => t.InvoiceAddress)
            .HasMaxLength(500);

        builder.Property(t => t.TrialStartDate)
            .IsRequired();

        builder.Property(t => t.SubscriptionStatus)
            .IsRequired();

        builder.Property(t => t.CreatedAt)
            .IsRequired();
    }
}
