apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Root kustomization for KDVManager production deployment
# This orchestrates all components using kustomize

resources:
- namespace.yml
- secrets/
- letsencrypt/
- crm/
- scheduling/
- web/
- envoy/
- data-migration/
- rabbitmq/

namespace: kdvmanager-prod

# Common labels applied to all resources
labels:
- pairs:
    app.kubernetes.io/name: kdvmanager
    app.kubernetes.io/part-of: kdvmanager
    app.kubernetes.io/managed-by: kustomize
    environment: production

# Common annotations
commonAnnotations:
  argocd.argoproj.io/managed: "true"
