# Pod Disruption Budgets for High Availability
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: web-pdb
  namespace: kdvmanager-prod
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: web
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: crm-api-pdb
  namespace: kdvmanager-prod
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: crm-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: scheduling-api-pdb
  namespace: kdvmanager-prod
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: scheduling-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: envoy-pdb
  namespace: kdvmanager-prod
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: envoy
