# Production-specific overrides for ArgoCD deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: kdvmanager-prod
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: web
        env:
        - name: REACT_APP_API_URL
          value: "https://api.kdvmanager.nl"
        - name: REACT_APP_ENVIRONMENT
          value: "production"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-api
  namespace: kdvmanager-prod
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: crm-pod
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:80"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduling-api
  namespace: kdvmanager-prod
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: scheduling-pod
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:80"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy
  namespace: kdvmanager-prod
spec:
  replicas: 2
