apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
    release: production
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0 
  selector:
    matchLabels:
      app: web
      release: production
  template:
    metadata:
      labels:
        app: web
        release: production
    spec:
      containers:
      - name: web
        image: ghcr.io/luukvh/kdvmanager/web:linux-master
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
          - name: https
            containerPort: 443
            protocol: TCP
