apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: kdvmanager-prod
  labels:
    app: web
    release: production
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 3
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0 
  selector:
    matchLabels:
      app: web
      release: production
  template:
    metadata:
      labels:
        app: web
        release: production
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: web
        image: ghcr.io/luukvh/kdvmanager/web:linux-master
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            memory: 256Mi
            cpu: 200m
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
