apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: kdvmanager-prod
  labels:
    app: web
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: web