---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: kdvmanager-prod
spec:
  encryptedData:
    .dockerconfigjson: AgArMi0wscj1akaBa/WHCDIHZIHyvrGQSza9sV0QiIqhOqykKetjdU5oyPDEqPbccXKLuVyDypDK7kJ06wqCNKppnb79q7wVYA8PrbN+mYtpHXewFqJjR9/ZCV0sXZCVUUd/BgFa5pp7IdOsaFLC2ISM2Uhd/xvXWjsRd///w8PPX7GKp7lE+4w5z9xgm/ZLcY6CmgW8Qc5snVthI7s0O9PGrUBPUJiHTAX5K/+rDtqZ3TxJK0nWCwaaWs+HlkR6r9uj3l4CFceWBuqWX/ekkcU8J9lALXbVvZP1VzDtDi3qL+UnimFvcEMReUdSpfknRVMtk40j2jcs2FoiYw6iPu5ASJc4yK43vlaxYWrZFcZEDFleeMf3s3Gbfd0F+BZB7VVub33kgXyDyeYyyYVbz6x9N7LzcaiRAEkc0ees03vQEOmIRVUemlLW4BPSXJXbxpUNPUWw1wf4Vsh5RoV9e7LCHIzQk3bu00yWLFGVdnSUZ8O18uNFbRcdJRJ9EmKh8s4gs3rPC45OFBxnPOQuFEqlsVN/9ct9+p477U1y5VqepsR1HIUw2tLdzN1DkoJWnoWfA/dwFnrUf20/9DfKK+T1AaynLmIttbRGSfIDYIl8hXxLy7L/W4k+Nj6I6kcngfWtqoxhwImzh2n3fwI9x9ylN/bosfYLdsN1+Y30IerCvXvCLs6oKfoTBjwVXYWPAfprdtC87NkM1ggbF001vHC8Cp6NW5dlqVto12iVpYdo6MLmO2E+DNymHpq07JjlF2gUXNOJPnABoDjJUkBlVJ/6qlMpT6J5ZjozdmoSfwgSSYiXbAoOpEnh1xFS+H1J+pqgxVuE2VmLoecyavpCuIDtt42PVUY90kv6/IgoO7sXk6lJgCafGeJj4suR1xpq//exkPbT45QbT7MH9F350Xk7zO6QEU/oolPwV2eO0t+/7PmTBU6ZKsqbddY211CGngfwwbI20YVk
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: kdvmanager-prod
    type: kubernetes.io/dockerconfigjson
