---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: kdvmanager-prod
spec:
  encryptedData:
    .dockerconfigjson: AgB+yroemEgMGqnTknnzSbUdVZz7M3Rlzn8Lsz4oU6Oq6rvWB3bift66cXzny+YhWLF7ybuvRIkVBUuW1HXlvpRTcvDN9Flljl793Pz8YnpYGc0wBurtVZSeXDvyKPflcM+SrkW0pYD/+24RWmYPPU3aMpbLZBoTUmzBlsyX3uKlBBS76qpwABysndoZ1dUySL+9cqwct30WJusstY2hsRubrD4anXGatendsoesRRO5OznyxTxF9DmEf7ySf0W1AoOxCerlP+5B3GQqd9SwuZbbKa6eEBzGLzqhX4ZVkCHgRDhzkfoU9zr8VN9APr0ZgUlB66OaPepsA8SHDtwe1K3ypq03plVL3PZQoYyJBTmQTNpzZ/ULjXA8XN79T6A0ozw8NdZbyq6XZkCg5N8qRyIDIGMWWcfyKC01wW0txBhOaduWlMx9d3rPMf1uIdnlbzg/6d4GqX4TBCTjhHE7gEUfg/N2TXacmoel6dpQRfchkoJ6jPSNkaNxcGxyCKOHppqOMytPrm2Mz9qB+om5wWy9dsFJQMhNDg8BcR2y8VUkL0zaI4y4DhVI02COwnIG3OmrlHcdMf+soURdc9fDCWdlTp+WESMb5ouy1FFCNBkZ4Gdu5Zk/FammSzEDkE2yCaZ8/qIqe064/rDbjy+uqUv1h809rS6ZQFo9YmiZYbrls6WancZgkM2B8J6F7HQJXFWOkTMNgjbrdowNQ3HC7WXpYfo+5GPdc3gVX9yO7LEraCe7hOpNVO/7IgJUUqVvOyfByVSMP+OPbPTe8zJ54lPAfOHPjQ9zpzHnUj44nf8qm6d070Lg+S7FHskhbtkbEGohq1vcZfdskkw+gSr4gM79OwCQ0vwYT2qvjtvQL+eXqNSG06sJ82o6tamyxDDSbWRkLuW23kgwj97SHPfVTJC+cB76T6V5OxXHEgg=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: kdvmanager-prod
    type: kubernetes.io/dockerconfigjson
