---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: kdvmanager-prod
spec:
  encryptedData:
    .dockerconfigjson: AgBM+vgeaWmHzf6m0460TQA8/3ddRoYeUy4E0JxQmBPDs22Pevl/nmKy8qeMyvp25EEGlf4dSmqqSDr8Sm+cM2mWeNA2H3fTuatPRLD+Lu/OClxob+QIFyJs98XrGvnnnCupbBRsOXEUx10c5wJmBncj19UUtj5JMmitoQm3S3HTktTl6CAnbNFI3Zb3kzMP2wxFsJbC3Z5O40HBu3sEKqJLlG0U7r0y2tE/r3WVDeZ0j5mGDUwycaxwRig2q5hQoNt31B5T3y62gO8EpKDF9FUeEYuNHAkqEZ4hZyVqckta3c+VYrNXGxdO39xhdSqz251fBEPP+rZQW/tEZzMSZfUDeWstOGYWWl7+2+cOugRRlvQjmN/Wu06W48R4poqql6yXUlZ2wUTRZ94Rs4yTsUaAAFdCIclkrPhEXHOT25LXCckWFPtLNI0ynal/S5bBEvB1HukfYHOa0Dck2RWVknTdmnE3T+fHPPMO3TvVySK06XC2DCXySJWiYslmarZyIC9ztnZb2rBMlFzL+NmQYy5THutETStlBChtThHwuYD/yY1F80reLUxBVCSt88R1TxeBgL2J5sdbTDzG7moF2UQPlxinFA7tJWiECk+Y1zwlnBP38E6kTLmW2QyrX0mTQs//y9F+VpOmSF7Z4eeoHoi5OCG8tcswWWK9qYebqhYbvNkNjG4Auz9sp6H1ZLTocEDPCv+HgiBuNZEIh37j87BWJOzOV1ijnMRmSGm0FUUe8qJbCK8iledQFqC0QaBjcoMY9sJwvOSb4tmiwzKyiI4FkOHibPHAQMvViEMNQdmFQN1Q7Bz5PkibyhOF+QHOTJRX+Yy1KsquuJxwTOs2Wv8sFWlDp2FcEjvcKBhDeZ5SUdG+2MJ/aJ4OGaXE57+TaEtHUAxvtrsWYCv7gJcfU/07xwmlCrxu4GyvcBmC1SWGcE3L//s+PNRGxX2Wlm+M4pJUGxVwCQpapseFsRZk8yfwHJnYvKjgsFYQrRLaFCaZifKMjmc4TC6t+JebABxcGnSIIwvHgk6pkxUM+PhfK4LT4J84/dq6jQrULkdwFM+KLOaTNGps0Efcc0oiYReD
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: kdvmanager-prod
    type: kubernetes.io/dockerconfigjson
