apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    name: cert-manager
    environment: production
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: certificate-management
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
