apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    name: observability
    environment: production
    app.kubernetes.io/name: observability-stack
    app.kubernetes.io/part-of: kdvmanager
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
