apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    name: observability
    environment: production
    app.kubernetes.io/name: observability-stack
    app.kubernetes.io/part-of: kdvmanager
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: v1.29
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/warn-version: v1.29
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/audit-version: v1.29
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
