apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy
  namespace: kdvmanager-prod
  labels:
    app: envoy
    release: production
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0 
  selector:
    matchLabels:
      app: envoy
      release: production
  template:
    metadata:
      labels:
        app: envoy
        release: production
    spec:
      serviceAccountName: kdvmanager-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: envoy
        image: envoyproxy/envoy:v1.31-latest
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          - name: https
            containerPort: 8443
            protocol: TCP
          - name: admin
            containerPort: 8001
            protocol: TCP
        startupProbe:
          httpGet:
            path: /ready
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /ready
            port: 8001
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          limits:
            memory: 256Mi
            cpu: 500m
          requests:
            memory: 128Mi
            cpu: 100m
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsUser: 1000
          runAsGroup: 1000
          capabilities:
            drop:
            - ALL
        env:
          - name: ENVOY_UID
            value: "1000"
          - name: ENVOY_GID
            value: "1000"
          - name: loglevel
            value: "info"
        volumeMounts:
          - name: tmp-volume
            mountPath: /tmp
          - name: envoy-config
            mountPath: /etc/envoy
            readOnly: true
        command: ["/usr/local/bin/envoy"]
        args: ["-c", "/etc/envoy/envoy.yaml", "--log-level", "info"]
      volumes:
        - name: tmp-volume
          emptyDir: {}
        - name: envoy-config
          configMap:
            name: envoy-config
