apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kdvmanager-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: "kdvmanager.nl"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: web
            port:
              number: 80
  - host: "api.kdvmanager.nl"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: envoy
            port:
              number: 80
  tls:
  - hosts:
    - kdvmanager.nl
    - api.kdvmanager.nl
    secretName: kdvmanager-nl-tls
