apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kdvmanager-ingress
  namespace: kdvmanager-prod
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
    argocd.argoproj.io/sync-wave: "3"
spec:
  rules:
  - host: "kdvmanager.nl"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: web
            port:
              number: 80
  - host: "api.kdvmanager.nl"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: envoy
            port:
              number: 80
