apiVersion: v1
kind: Service
metadata:
  name: envoy
  namespace: kdvmanager-prod
  labels:
    app: envoy
    release: production
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8443
    protocol: TCP
  selector:
    app: envoy
