apiVersion: v1
kind: Service
metadata:
  name: envoy
  namespace: kdvmanager-prod
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: envoy
