name: "Build and push image"
description: "Builds and pushes an image to a registry"

inputs:
  service:
    description: "Service to build"
    required: true
  registry_host:
    description: "Image registry host e.g. myacr.azureacr.io"
    required: true
  registry_endpoint:
    description: "Image registry repo e.g. myacr.azureacr.io/eshop"
    required: true
  image_name:
    description: "Name of image"
    required: true
  registry_username:
    description: "Registry username"
    required: true
  registry_password:
    description: "Registry password"
    required: true
  nuget_github_token:
    description: "GitHub NuGet token for private packages"
  
runs:
  using: "composite"
  steps:
  - name: Login to the Container Registry
    uses: docker/login-action@v3
    with:
      registry: ${{ inputs.registry_host }}
      username: ${{ inputs.registry_username }}
      password: ${{ inputs.registry_password }}

  - name: Set branch name as env variable
    run: |
      currentbranch=$(echo ${GITHUB_REF##*/})
      echo "running on $currentbranch"
      echo "BRANCH=$currentbranch" >> $GITHUB_ENV
      SHORT_SHA=${GITHUB_SHA::7}
      echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
    shell: bash

  - name: Compose build ${{ inputs.service }}
    shell: bash
    run: sudo -E docker compose  -f docker-compose.yml build ${{ inputs.service }}
    working-directory: ./src
    env:
      TAG: ${{ env.BRANCH }}
      REGISTRY: ${{ inputs.registry_endpoint }}
      NUGET_GITHUB_TOKEN: ${{ inputs.nuget_github_token }}

  - name: Tag image with short SHA
    shell: bash
    run: |
      image="${{ inputs.registry_endpoint }}/${{ inputs.image_name }}:linux-${{ env.BRANCH }}"
      sha_tag="${{ inputs.registry_endpoint }}/${{ inputs.image_name }}:linux-${{ env.SHORT_SHA }}"
      echo "Tagging $image as $sha_tag"
      docker tag "$image" "$sha_tag"

  - name: Compose push  -f docker-compose.yml ${{ inputs.service }}
    shell: bash
    run: sudo -E docker compose push ${{ inputs.service }}
    working-directory: ./src
    env:
      TAG: ${{ env.BRANCH }}
      REGISTRY: ${{ inputs.registry_endpoint }}

  - name: Push short SHA tag
    shell: bash
    run: |
      docker push "${{ inputs.registry_endpoint }}/${{ inputs.image_name }}:linux-${{ env.SHORT_SHA }}"
