/**
 * Generated by orval v6.5.1 🍺
 * Do not edit manually.
 * KDVManager.Services.ChildManagement.Api
 * OpenAPI spec version: 1.0
 */
import {
  useQuery,
  useMutation,
  UseQueryOptions,
  UseMutationOptions,
  QueryFunction,
  MutationFunction,
  UseQueryResult,
  QueryKey,
} from "react-query";
import type { ChildListVM, CreateChildCommand } from "../../models";
import { executeAxios } from "../../mutator/executeAxios";

type AsyncReturnType<T extends (...args: any) => Promise<any>> = T extends (
  ...args: any
) => Promise<infer R>
  ? R
  : any;

export const getAllChildren = () => {
  return executeAxios<ChildListVM[]>({ url: `/api/Children`, method: "get" });
};

export const getGetAllChildrenQueryKey = () => [`/api/Children`];

export const useGetAllChildren = <
  TData = AsyncReturnType<typeof getAllChildren>,
  TError = unknown
>(options?: {
  query?: UseQueryOptions<
    AsyncReturnType<typeof getAllChildren>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const { query: queryOptions } = options || {};

  const queryKey = queryOptions?.queryKey ?? getGetAllChildrenQueryKey();

  const queryFn: QueryFunction<AsyncReturnType<typeof getAllChildren>> = () =>
    getAllChildren();

  const query = useQuery<AsyncReturnType<typeof getAllChildren>, TError, TData>(
    queryKey,
    queryFn,
    queryOptions
  );

  return {
    queryKey,
    ...query,
  };
};

export const createChild = (createChildCommand: CreateChildCommand) => {
  return executeAxios<string>({
    url: `/api/Children`,
    method: "post",
    data: createChildCommand,
  });
};

export const useCreateChild = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    AsyncReturnType<typeof createChild>,
    TError,
    { data: CreateChildCommand },
    TContext
  >;
}) => {
  const { mutation: mutationOptions } = options || {};

  const mutationFn: MutationFunction<
    AsyncReturnType<typeof createChild>,
    { data: CreateChildCommand }
  > = (props) => {
    const { data } = props || {};

    return createChild(data);
  };

  return useMutation<
    AsyncReturnType<typeof createChild>,
    TError,
    { data: CreateChildCommand },
    TContext
  >(mutationFn, mutationOptions);
};
