/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { AddChildCommand } from "../../models/addChildCommand";

import type { ChildDetailVM } from "../../models/childDetailVM";

import type { ChildListVM } from "../../models/childListVM";

import type { ListChildrenParams } from "../../models/listChildrenParams";

import type { UnprocessableEntityResponse } from "../../models/unprocessableEntityResponse";

import type { UpdateChildCommand } from "../../models/updateChildCommand";

import { executeFetchPaginated } from "../../mutator/executeFetchPaginated";
import { executeFetch } from "../../mutator/executeFetch";

export const listChildren = (params: ListChildrenParams, signal?: AbortSignal) => {
  return executeFetchPaginated<ChildListVM[]>({
    url: `/crm/v1/children`,
    method: "GET",
    params,
    signal,
  });
};

export const getListChildrenQueryKey = (params: ListChildrenParams) => {
  return [`/crm/v1/children`, ...(params ? [params] : [])] as const;
};

export const getListChildrenQueryOptions = <
  TData = Awaited<ReturnType<typeof listChildren>>,
  TError = unknown,
>(
  params: ListChildrenParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listChildren>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListChildrenQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listChildren>>> = ({ signal }) =>
    listChildren(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listChildren>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListChildrenQueryResult = NonNullable<Awaited<ReturnType<typeof listChildren>>>;
export type ListChildrenQueryError = unknown;

export function useListChildren<TData = Awaited<ReturnType<typeof listChildren>>, TError = unknown>(
  params: ListChildrenParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listChildren>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listChildren>>,
          TError,
          Awaited<ReturnType<typeof listChildren>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListChildren<TData = Awaited<ReturnType<typeof listChildren>>, TError = unknown>(
  params: ListChildrenParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listChildren>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listChildren>>,
          TError,
          Awaited<ReturnType<typeof listChildren>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListChildren<TData = Awaited<ReturnType<typeof listChildren>>, TError = unknown>(
  params: ListChildrenParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listChildren>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useListChildren<TData = Awaited<ReturnType<typeof listChildren>>, TError = unknown>(
  params: ListChildrenParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listChildren>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListChildrenQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const addChild = (addChildCommand: AddChildCommand, signal?: AbortSignal) => {
  return executeFetch<string>({
    url: `/crm/v1/children`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: addChildCommand,
    signal,
  });
};

export const getAddChildMutationOptions = <
  TError = UnprocessableEntityResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addChild>>,
    TError,
    { data: AddChildCommand },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addChild>>,
  TError,
  { data: AddChildCommand },
  TContext
> => {
  const mutationKey = ["addChild"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addChild>>,
    { data: AddChildCommand }
  > = (props) => {
    const { data } = props ?? {};

    return addChild(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddChildMutationResult = NonNullable<Awaited<ReturnType<typeof addChild>>>;
export type AddChildMutationBody = AddChildCommand;
export type AddChildMutationError = UnprocessableEntityResponse;

export const useAddChild = <TError = UnprocessableEntityResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addChild>>,
      TError,
      { data: AddChildCommand },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof addChild>>,
  TError,
  { data: AddChildCommand },
  TContext
> => {
  const mutationOptions = getAddChildMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getChildById = (id: string, signal?: AbortSignal) => {
  return executeFetch<ChildDetailVM>({ url: `/crm/v1/children/${id}`, method: "GET", signal });
};

export const getGetChildByIdQueryKey = (id: string) => {
  return [`/crm/v1/children/${id}`] as const;
};

export const getGetChildByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getChildById>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getChildById>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetChildByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getChildById>>> = ({ signal }) =>
    getChildById(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getChildById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetChildByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getChildById>>>;
export type GetChildByIdQueryError = unknown;

export function useGetChildById<TData = Awaited<ReturnType<typeof getChildById>>, TError = unknown>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getChildById>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChildById>>,
          TError,
          Awaited<ReturnType<typeof getChildById>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetChildById<TData = Awaited<ReturnType<typeof getChildById>>, TError = unknown>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getChildById>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChildById>>,
          TError,
          Awaited<ReturnType<typeof getChildById>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetChildById<TData = Awaited<ReturnType<typeof getChildById>>, TError = unknown>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getChildById>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetChildById<TData = Awaited<ReturnType<typeof getChildById>>, TError = unknown>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getChildById>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetChildByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const updateChild = (id: string, updateChildCommand: UpdateChildCommand) => {
  return executeFetch<void>({
    url: `/crm/v1/children/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: updateChildCommand,
  });
};

export const getUpdateChildMutationOptions = <
  TError = UnprocessableEntityResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateChild>>,
    TError,
    { id: string; data: UpdateChildCommand },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateChild>>,
  TError,
  { id: string; data: UpdateChildCommand },
  TContext
> => {
  const mutationKey = ["updateChild"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateChild>>,
    { id: string; data: UpdateChildCommand }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateChild(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateChildMutationResult = NonNullable<Awaited<ReturnType<typeof updateChild>>>;
export type UpdateChildMutationBody = UpdateChildCommand;
export type UpdateChildMutationError = UnprocessableEntityResponse;

export const useUpdateChild = <TError = UnprocessableEntityResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateChild>>,
      TError,
      { id: string; data: UpdateChildCommand },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateChild>>,
  TError,
  { id: string; data: UpdateChildCommand },
  TContext
> => {
  const mutationOptions = getUpdateChildMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const deleteChild = (id: string) => {
  return executeFetch<void>({ url: `/crm/v1/children/${id}`, method: "DELETE" });
};

export const getDeleteChildMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteChild>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteChild>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteChild"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteChild>>, { id: string }> = (
    props,
  ) => {
    const { id } = props ?? {};

    return deleteChild(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteChildMutationResult = NonNullable<Awaited<ReturnType<typeof deleteChild>>>;

export type DeleteChildMutationError = unknown;

export const useDeleteChild = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteChild>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof deleteChild>>, TError, { id: string }, TContext> => {
  const mutationOptions = getDeleteChildMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getNextChildNumber = (signal?: AbortSignal) => {
  return executeFetch<number>({ url: `/crm/v1/children/next-number`, method: "GET", signal });
};

export const getGetNextChildNumberQueryKey = () => {
  return [`/crm/v1/children/next-number`] as const;
};

export const getGetNextChildNumberQueryOptions = <
  TData = Awaited<ReturnType<typeof getNextChildNumber>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getNextChildNumber>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetNextChildNumberQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getNextChildNumber>>> = ({ signal }) =>
    getNextChildNumber(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getNextChildNumber>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetNextChildNumberQueryResult = NonNullable<
  Awaited<ReturnType<typeof getNextChildNumber>>
>;
export type GetNextChildNumberQueryError = unknown;

export function useGetNextChildNumber<
  TData = Awaited<ReturnType<typeof getNextChildNumber>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getNextChildNumber>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNextChildNumber>>,
          TError,
          Awaited<ReturnType<typeof getNextChildNumber>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetNextChildNumber<
  TData = Awaited<ReturnType<typeof getNextChildNumber>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getNextChildNumber>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNextChildNumber>>,
          TError,
          Awaited<ReturnType<typeof getNextChildNumber>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetNextChildNumber<
  TData = Awaited<ReturnType<typeof getNextChildNumber>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getNextChildNumber>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetNextChildNumber<
  TData = Awaited<ReturnType<typeof getNextChildNumber>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getNextChildNumber>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetNextChildNumberQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
