apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resource-quota.yaml
- limit-range.yaml

labels:
- pairs:
    component: resource-management
    app.kubernetes.io/name: kdvmanager-resource-management
    app.kubernetes.io/part-of: kdvmanager
    app.kubernetes.io/managed-by: kustomize