apiVersion: v1
kind: LimitRange
metadata:
  name: kdvmanager-prod-limits
  namespace: kdvmanager-prod
spec:
  limits:
  - type: Container
    default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    max:
      cpu: "2"
      memory: 2Gi
    min:
      cpu: 50m
      memory: 32Mi
  - type: Pod
    max:
      cpu: "4"
      memory: 4Gi