apiVersion: v1
kind: ResourceQuota
metadata:
  name: kdvmanager-prod-quota
  namespace: kdvmanager-prod
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "8"
    limits.memory: 8Gi
    pods: "20"
    services: "10"
    configmaps: "20"
    secrets: "20"
    persistentvolumeclaims: "5"