apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- production_issuer.yml
- staging_issuer.yml

# Note: These are ClusterIssuers that don't inherit the main namespace
# They explicitly define their own namespace (cert-manager)

labels:
- pairs:
    component: certificates
    service: letsencrypt
