apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: kdvmanager-prod
  labels:
    app: rabbitmq
    component: messaging
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:4-management
        ports:
        - containerPort: 5672
        - containerPort: 15672
        envFrom:
        - secretRef:
            name: rabbitmq-secret
        resources:
            # Reduced footprint; increase if queues grow or paging observed
            requests:
              cpu: 40m
              memory: 160Mi
            limits:
              cpu: 250m
              memory: 384Mi
