apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service-account.yml
- ghcr-secret.yaml
- kdvmanager-postgres-secret.yaml
- mssql-source-secret.yaml
- rabbitmq-secret.yaml

labels:
- pairs:
    component: security
    service: secrets
