admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          upgrade_configs:
          - upgrade_type: websocket
          route_config:
            name: kdvmanager_backend_route
            virtual_hosts:
            - name: kdvmanager_backend
              domains:
                - "api.*"
              cors:
                allow_origin_string_match:
                  - prefix: "*"
                allow_methods: GET, POST, PUT, HEAD, OPTIONS, DELETE
                allow_headers: Authorization,Content-Type,Link,Total,Per-Page
              routes:
              - name: "children"
                match:
                  prefix: "/v1/children"
                route:
                  auto_host_rewrite: true
                  cluster: childmanagement-api
            - name: kdvmanager_web
              domains:
              - "*"
              routes:
              - name: "web"
                match:
                  prefix: "/"
                route:
                  auto_host_rewrite: true
                  prefix_rewrite: "/"
                  cluster: web
          http_filters:
          - name: envoy.filters.http.cors
          - name: envoy.filters.http.router
  clusters:
  - name: web
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: web
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: web
                port_value: 80
  - name: childmanagement-api
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: childmanagement-api
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: childmanagement-api
                port_value: 80
  - name: docs
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: docs
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: documentation.api
                port_value: 80