/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { AddScheduleCommand } from "../../models/addScheduleCommand";

import type { ChildScheduleListVM } from "../../models/childScheduleListVM";

import type { GetChildSchedulesParams } from "../../models/getChildSchedulesParams";

import type { GetGroupSummaryParams } from "../../models/getGroupSummaryParams";

import type { GetLongTermPlanningParams } from "../../models/getLongTermPlanningParams";

import type { GetPrintSchedulesParams } from "../../models/getPrintSchedulesParams";

import type { GetSchedulesByDateParams } from "../../models/getSchedulesByDateParams";

import type { GroupSummaryVM } from "../../models/groupSummaryVM";

import type { LongTermPlanningVM } from "../../models/longTermPlanningVM";

import type { PrintSchedulesVM } from "../../models/printSchedulesVM";

import type { ProblemDetails } from "../../models/problemDetails";

import type { ScheduleByDateVM } from "../../models/scheduleByDateVM";

import type { UnprocessableEntityResponse1 } from "../../models/unprocessableEntityResponse1";

import { executeFetch } from "../../mutator/executeFetch";

export const getChildSchedules = (params?: GetChildSchedulesParams, signal?: AbortSignal) => {
  return executeFetch<ChildScheduleListVM[]>({
    url: `/scheduling/v1/schedules`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetChildSchedulesQueryKey = (params?: GetChildSchedulesParams) => {
  return [`/scheduling/v1/schedules`, ...(params ? [params] : [])] as const;
};

export const getGetChildSchedulesQueryOptions = <
  TData = Awaited<ReturnType<typeof getChildSchedules>>,
  TError = unknown,
>(
  params?: GetChildSchedulesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getChildSchedules>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetChildSchedulesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getChildSchedules>>> = ({ signal }) =>
    getChildSchedules(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getChildSchedules>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetChildSchedulesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getChildSchedules>>
>;
export type GetChildSchedulesQueryError = unknown;

export function useGetChildSchedules<
  TData = Awaited<ReturnType<typeof getChildSchedules>>,
  TError = unknown,
>(
  params: undefined | GetChildSchedulesParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getChildSchedules>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChildSchedules>>,
          TError,
          Awaited<ReturnType<typeof getChildSchedules>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetChildSchedules<
  TData = Awaited<ReturnType<typeof getChildSchedules>>,
  TError = unknown,
>(
  params?: GetChildSchedulesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getChildSchedules>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChildSchedules>>,
          TError,
          Awaited<ReturnType<typeof getChildSchedules>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetChildSchedules<
  TData = Awaited<ReturnType<typeof getChildSchedules>>,
  TError = unknown,
>(
  params?: GetChildSchedulesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getChildSchedules>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetChildSchedules<
  TData = Awaited<ReturnType<typeof getChildSchedules>>,
  TError = unknown,
>(
  params?: GetChildSchedulesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getChildSchedules>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetChildSchedulesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const addSchedule = (addScheduleCommand: AddScheduleCommand, signal?: AbortSignal) => {
  return executeFetch<string>({
    url: `/scheduling/v1/schedules`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: addScheduleCommand,
    signal,
  });
};

export const getAddScheduleMutationOptions = <
  TError = UnprocessableEntityResponse1,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addSchedule>>,
    TError,
    { data: AddScheduleCommand },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addSchedule>>,
  TError,
  { data: AddScheduleCommand },
  TContext
> => {
  const mutationKey = ["addSchedule"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addSchedule>>,
    { data: AddScheduleCommand }
  > = (props) => {
    const { data } = props ?? {};

    return addSchedule(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddScheduleMutationResult = NonNullable<Awaited<ReturnType<typeof addSchedule>>>;
export type AddScheduleMutationBody = AddScheduleCommand;
export type AddScheduleMutationError = UnprocessableEntityResponse1;

export const useAddSchedule = <TError = UnprocessableEntityResponse1, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addSchedule>>,
      TError,
      { data: AddScheduleCommand },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof addSchedule>>,
  TError,
  { data: AddScheduleCommand },
  TContext
> => {
  const mutationOptions = getAddScheduleMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getSchedulesByDate = (params?: GetSchedulesByDateParams, signal?: AbortSignal) => {
  return executeFetch<ScheduleByDateVM[]>({
    url: `/scheduling/v1/schedules/daterange`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetSchedulesByDateQueryKey = (params?: GetSchedulesByDateParams) => {
  return [`/scheduling/v1/schedules/daterange`, ...(params ? [params] : [])] as const;
};

export const getGetSchedulesByDateQueryOptions = <
  TData = Awaited<ReturnType<typeof getSchedulesByDate>>,
  TError = unknown,
>(
  params?: GetSchedulesByDateParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchedulesByDate>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSchedulesByDateQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSchedulesByDate>>> = ({ signal }) =>
    getSchedulesByDate(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSchedulesByDate>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSchedulesByDateQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSchedulesByDate>>
>;
export type GetSchedulesByDateQueryError = unknown;

export function useGetSchedulesByDate<
  TData = Awaited<ReturnType<typeof getSchedulesByDate>>,
  TError = unknown,
>(
  params: undefined | GetSchedulesByDateParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchedulesByDate>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSchedulesByDate>>,
          TError,
          Awaited<ReturnType<typeof getSchedulesByDate>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSchedulesByDate<
  TData = Awaited<ReturnType<typeof getSchedulesByDate>>,
  TError = unknown,
>(
  params?: GetSchedulesByDateParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSchedulesByDate>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSchedulesByDate>>,
          TError,
          Awaited<ReturnType<typeof getSchedulesByDate>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSchedulesByDate<
  TData = Awaited<ReturnType<typeof getSchedulesByDate>>,
  TError = unknown,
>(
  params?: GetSchedulesByDateParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchedulesByDate>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetSchedulesByDate<
  TData = Awaited<ReturnType<typeof getSchedulesByDate>>,
  TError = unknown,
>(
  params?: GetSchedulesByDateParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSchedulesByDate>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSchedulesByDateQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGroupSummary = (params?: GetGroupSummaryParams, signal?: AbortSignal) => {
  return executeFetch<GroupSummaryVM>({
    url: `/scheduling/v1/schedules/group-summary`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetGroupSummaryQueryKey = (params?: GetGroupSummaryParams) => {
  return [`/scheduling/v1/schedules/group-summary`, ...(params ? [params] : [])] as const;
};

export const getGetGroupSummaryQueryOptions = <
  TData = Awaited<ReturnType<typeof getGroupSummary>>,
  TError = unknown,
>(
  params?: GetGroupSummaryParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getGroupSummary>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetGroupSummaryQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getGroupSummary>>> = ({ signal }) =>
    getGroupSummary(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getGroupSummary>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetGroupSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getGroupSummary>>>;
export type GetGroupSummaryQueryError = unknown;

export function useGetGroupSummary<
  TData = Awaited<ReturnType<typeof getGroupSummary>>,
  TError = unknown,
>(
  params: undefined | GetGroupSummaryParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getGroupSummary>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGroupSummary>>,
          TError,
          Awaited<ReturnType<typeof getGroupSummary>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetGroupSummary<
  TData = Awaited<ReturnType<typeof getGroupSummary>>,
  TError = unknown,
>(
  params?: GetGroupSummaryParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getGroupSummary>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGroupSummary>>,
          TError,
          Awaited<ReturnType<typeof getGroupSummary>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetGroupSummary<
  TData = Awaited<ReturnType<typeof getGroupSummary>>,
  TError = unknown,
>(
  params?: GetGroupSummaryParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getGroupSummary>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetGroupSummary<
  TData = Awaited<ReturnType<typeof getGroupSummary>>,
  TError = unknown,
>(
  params?: GetGroupSummaryParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getGroupSummary>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetGroupSummaryQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getPrintSchedules = (params?: GetPrintSchedulesParams, signal?: AbortSignal) => {
  return executeFetch<PrintSchedulesVM>({
    url: `/scheduling/v1/schedules/print`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetPrintSchedulesQueryKey = (params?: GetPrintSchedulesParams) => {
  return [`/scheduling/v1/schedules/print`, ...(params ? [params] : [])] as const;
};

export const getGetPrintSchedulesQueryOptions = <
  TData = Awaited<ReturnType<typeof getPrintSchedules>>,
  TError = unknown,
>(
  params?: GetPrintSchedulesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrintSchedules>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPrintSchedulesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPrintSchedules>>> = ({ signal }) =>
    getPrintSchedules(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPrintSchedules>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPrintSchedulesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPrintSchedules>>
>;
export type GetPrintSchedulesQueryError = unknown;

export function useGetPrintSchedules<
  TData = Awaited<ReturnType<typeof getPrintSchedules>>,
  TError = unknown,
>(
  params: undefined | GetPrintSchedulesParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrintSchedules>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPrintSchedules>>,
          TError,
          Awaited<ReturnType<typeof getPrintSchedules>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetPrintSchedules<
  TData = Awaited<ReturnType<typeof getPrintSchedules>>,
  TError = unknown,
>(
  params?: GetPrintSchedulesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrintSchedules>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPrintSchedules>>,
          TError,
          Awaited<ReturnType<typeof getPrintSchedules>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetPrintSchedules<
  TData = Awaited<ReturnType<typeof getPrintSchedules>>,
  TError = unknown,
>(
  params?: GetPrintSchedulesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrintSchedules>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetPrintSchedules<
  TData = Awaited<ReturnType<typeof getPrintSchedules>>,
  TError = unknown,
>(
  params?: GetPrintSchedulesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrintSchedules>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetPrintSchedulesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getLongTermPlanning = (params?: GetLongTermPlanningParams, signal?: AbortSignal) => {
  return executeFetch<LongTermPlanningVM>({
    url: `/scheduling/v1/schedules/long-term-planning`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetLongTermPlanningQueryKey = (params?: GetLongTermPlanningParams) => {
  return [`/scheduling/v1/schedules/long-term-planning`, ...(params ? [params] : [])] as const;
};

export const getGetLongTermPlanningQueryOptions = <
  TData = Awaited<ReturnType<typeof getLongTermPlanning>>,
  TError = unknown,
>(
  params?: GetLongTermPlanningParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLongTermPlanning>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetLongTermPlanningQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getLongTermPlanning>>> = ({ signal }) =>
    getLongTermPlanning(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getLongTermPlanning>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetLongTermPlanningQueryResult = NonNullable<
  Awaited<ReturnType<typeof getLongTermPlanning>>
>;
export type GetLongTermPlanningQueryError = unknown;

export function useGetLongTermPlanning<
  TData = Awaited<ReturnType<typeof getLongTermPlanning>>,
  TError = unknown,
>(
  params: undefined | GetLongTermPlanningParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLongTermPlanning>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLongTermPlanning>>,
          TError,
          Awaited<ReturnType<typeof getLongTermPlanning>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetLongTermPlanning<
  TData = Awaited<ReturnType<typeof getLongTermPlanning>>,
  TError = unknown,
>(
  params?: GetLongTermPlanningParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLongTermPlanning>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLongTermPlanning>>,
          TError,
          Awaited<ReturnType<typeof getLongTermPlanning>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetLongTermPlanning<
  TData = Awaited<ReturnType<typeof getLongTermPlanning>>,
  TError = unknown,
>(
  params?: GetLongTermPlanningParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLongTermPlanning>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetLongTermPlanning<
  TData = Awaited<ReturnType<typeof getLongTermPlanning>>,
  TError = unknown,
>(
  params?: GetLongTermPlanningParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLongTermPlanning>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetLongTermPlanningQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const deleteSchedule = (id: string) => {
  return executeFetch<void>({ url: `/scheduling/v1/schedules/${id}`, method: "DELETE" });
};

export const getDeleteScheduleMutationOptions = <
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteSchedule>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteSchedule>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteSchedule"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteSchedule>>, { id: string }> = (
    props,
  ) => {
    const { id } = props ?? {};

    return deleteSchedule(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteScheduleMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSchedule>>>;

export type DeleteScheduleMutationError = ProblemDetails;

export const useDeleteSchedule = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteSchedule>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteSchedule>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteScheduleMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
