/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import type { PhoneNumberType } from "./phoneNumberType";

export type AddPhoneNumberDto = {
  number?: string;
  type?: PhoneNumberType;
};
