/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */

export type AdministratorListVM = {
  id: string;
  name: string;
  email: string;
  createdAt: string;
};
