/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */

export type AdministratorListVM = {
  /** Auth0 user id (sub) for active members, or the invitation id for pending invitations. */
  id: string;
  email: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  picture?: string | null;
  /** "Active" for organization members, "Pending" for outstanding invitations. */
  status: string;
};
