/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import type { GuardianRelationshipType } from "./guardianRelationshipType";

export type ChildRelationshipVM = {
  childId?: string;
  childName: string;
  dateOfBirth?: string;
  relationshipType?: GuardianRelationshipType;
  isPrimaryContact?: boolean;
  isEmergencyContact?: boolean;
};
