/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import type { ChildSchedulingStatus } from "./childSchedulingStatus";

export type ChildListVM = {
  id: string;
  fullName: string;
  dateOfBirth: string;
  childNumber: number;
  schedulingStatus: ChildSchedulingStatus;
  /** @nullable */
  statusRelevantDate?: string | null;
};
