/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import type { ChildSchedulingStatus } from "./childSchedulingStatus";

export type ChildDetailVM = {
  id?: string;
  givenName: string;
  familyName: string;
  dateOfBirth?: string;
  /** @nullable */
  cid?: string | null;
  childNumber?: number;
  schedulingStatus?: ChildSchedulingStatus;
  /** @nullable */
  statusRelevantDate?: string | null;
};
