/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */

export type ChildSchedulingStatus =
  (typeof ChildSchedulingStatus)[keyof typeof ChildSchedulingStatus];

export const ChildSchedulingStatus = {
  NoPlanning: "NoPlanning",
  Past: "Past",
  Active: "Active",
  Upcoming: "Upcoming",
} as const;
