/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import type { GuardianRelationshipType } from "./guardianRelationshipType";

export type GuardianChildVM = {
  childId?: string;
  fullName: string;
  dateOfBirth?: string;
  age?: number;
  relationshipType?: GuardianRelationshipType;
  isPrimaryContact?: boolean;
  isEmergencyContact?: boolean;
};
