/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */

export type ListGuardiansParams = {
  search?: string;
  /**
   * @minimum 1
   * @maximum 2147483647
   */
  pageNumber?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  pageSize?: number;
};
