/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import type { NewsletterRecipientVM } from "./newsletterRecipientVM";

export type NewsletterRecipientsResponse = {
  year: number;
  month: number;
  generatedAt: string;
  totalActiveChildren: number;
  recipients: NewsletterRecipientVM[];
};
