/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */

export type NewsletterRecipientVM = {
  guardianId: string;
  fullName: string;
  email: string;
};
