/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import type { PhoneListChildVM } from "./phoneListChildVM";

export type PhoneListResponse = {
  year: number;
  generatedAt: string;
  children: PhoneListChildVM[];
};
