/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */

export type PhoneNumberType = (typeof PhoneNumberType)[keyof typeof PhoneNumberType];

export const PhoneNumberType = {
  Mobile: "Mobile",
  Home: "Home",
  Work: "Work",
  Other: "Other",
} as const;
