/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import type { PhoneListGuardianVM } from "./phoneListGuardianVM";

export type PhoneListChildVM = {
  id: string;
  fullName: string;
  dateOfBirth: string;
  childNumber: number;
  guardians: PhoneListGuardianVM[];
};
