/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import type { PhoneNumberType } from "./phoneNumberType";

export type PhoneListPhoneNumberVM = {
  number: string;
  type: PhoneNumberType;
};
