/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */

export type UpdateChildCommand = {
  id: string;
  /** @nullable */
  givenName: string | null;
  /** @nullable */
  familyName: string | null;
  /** @nullable */
  dateOfBirth: string | null;
  /** @nullable */
  allergies?: string | null;
  /** @nullable */
  medication?: string | null;
  /** @nullable */
  dietaryRequirements?: string | null;
  /** @nullable */
  medicalNotes?: string | null;
};
