/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import type { PhoneNumberType } from "./phoneNumberType";

export type UpdatePhoneNumberDto = {
  /** @nullable */
  id?: string | null;
  number?: string;
  type?: PhoneNumberType;
};
