/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import type { UpdatePhoneNumberDto } from "./updatePhoneNumberDto";

export type UpdateGuardianCommand = {
  id: string;
  givenName: string;
  familyName: string;
  dateOfBirth: string;
  email: string;
  phoneNumbers?: UpdatePhoneNumberDto[];
};
