apiVersion: v1
kind: Service
metadata:
  name: crm-api
  namespace: kdvmanager-prod
  labels:
    app: crm-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: crm-api
    release: production
