apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0 
  selector:
    matchLabels:
      app: web
      release: production
  template:
    metadata:
      labels:
        app: web
        release: production
    spec:
      serviceAccountName: kdvmanager-sa
      containers:
      - name: web
        image: ghcr.io/luuklabs/kdvmanager/web:linux-main
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
          - name: https
            containerPort: 443
            protocol: TCP
        resources:
          limits:
            memory: 100Mi
            cpu: 500m
          requests:
            memory: 50Mi
            cpu: 100m
        env:
          # Configure OpenTelemetry exporter URL exposed via an ingress to the collector (HTTP /v1/traces).
          - name: VITE_OTEL_EXPORTER_URL
            value: "https://otel.kdvmanager.nl"
          - name: VITE_DEPLOY_ENV
            value: "production"
        