apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yml
- service.yml

labels:
- pairs:
    app: web
    component: frontend
    service: web

images:
- name: ghcr.io/luuklabs/kdvmanager/web
  newName: ghcr.io/luuklabs/kdvmanager/web
  newTag: linux-587aa33
