---
apiVersion: getambassador.io/v3alpha1
kind:  Mapping
metadata:
  name:  cors
spec:
  prefix: /cors/
  service: cors-example
  cors:
    origins: 
    - '*'
    methods: 
    - POST
    - GET
    - OPTIONS
    headers: 
    - Content-Type
    exposed_headers: 
    - X-Custom-Header
    max_age: "86400"