apiVersion: v1
kind: Service
metadata:
  name: apigw
  namespace: kdvmanager
  labels:
    app: apigw
    release: production
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 8001
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    app: apigw
    release: production