/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * KDVManager Tenants API
 * OpenAPI spec version: v1
 */

export type ListTenantsParams = {
  pageNumber?: number;
  pageSize?: number;
  /** @nullable */
  search?: string | null;
};
