/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * KDVManager Tenants API
 * OpenAPI spec version: v1
 */

export type TenantListVM = {
  id: string;
  name: string;
  isActive: boolean;
  createdAt: string;
};
