apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kdvmanager
  namespace: argocd
  labels:
    app.kubernetes.io/name: kdvmanager
    app.kubernetes.io/part-of: kdvmanager-stack
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/LuukLabs/KDVManager
    targetRevision: main
    path: deploy/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: kdvmanager-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
