/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { EndMarkSettingsDto } from "../../models/endMarkSettingsDto";

import type { UpdateEndMarkSettingsCommand } from "../../models/updateEndMarkSettingsCommand";

import { executeFetch } from "../../mutator/executeFetch";

export const getEndMarkSettings = (signal?: AbortSignal) => {
  return executeFetch<EndMarkSettingsDto>({
    url: `/scheduling/v1/endmarksettings`,
    method: "GET",
    signal,
  });
};

export const getGetEndMarkSettingsQueryKey = () => {
  return [`/scheduling/v1/endmarksettings`] as const;
};

export const getGetEndMarkSettingsQueryOptions = <
  TData = Awaited<ReturnType<typeof getEndMarkSettings>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getEndMarkSettings>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetEndMarkSettingsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getEndMarkSettings>>> = ({ signal }) =>
    getEndMarkSettings(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getEndMarkSettings>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetEndMarkSettingsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getEndMarkSettings>>
>;
export type GetEndMarkSettingsQueryError = unknown;

export function useGetEndMarkSettings<
  TData = Awaited<ReturnType<typeof getEndMarkSettings>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getEndMarkSettings>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEndMarkSettings>>,
          TError,
          Awaited<ReturnType<typeof getEndMarkSettings>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetEndMarkSettings<
  TData = Awaited<ReturnType<typeof getEndMarkSettings>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEndMarkSettings>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEndMarkSettings>>,
          TError,
          Awaited<ReturnType<typeof getEndMarkSettings>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetEndMarkSettings<
  TData = Awaited<ReturnType<typeof getEndMarkSettings>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getEndMarkSettings>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetEndMarkSettings<
  TData = Awaited<ReturnType<typeof getEndMarkSettings>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getEndMarkSettings>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetEndMarkSettingsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const updateEndMarkSettings = (
  updateEndMarkSettingsCommand: UpdateEndMarkSettingsCommand,
) => {
  return executeFetch<null>({
    url: `/scheduling/v1/endmarksettings`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: updateEndMarkSettingsCommand,
  });
};

export const getUpdateEndMarkSettingsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateEndMarkSettings>>,
    TError,
    { data: UpdateEndMarkSettingsCommand },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateEndMarkSettings>>,
  TError,
  { data: UpdateEndMarkSettingsCommand },
  TContext
> => {
  const mutationKey = ["updateEndMarkSettings"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateEndMarkSettings>>,
    { data: UpdateEndMarkSettingsCommand }
  > = (props) => {
    const { data } = props ?? {};

    return updateEndMarkSettings(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateEndMarkSettingsMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateEndMarkSettings>>
>;
export type UpdateEndMarkSettingsMutationBody = UpdateEndMarkSettingsCommand;
export type UpdateEndMarkSettingsMutationError = unknown;

export const useUpdateEndMarkSettings = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateEndMarkSettings>>,
      TError,
      { data: UpdateEndMarkSettingsCommand },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateEndMarkSettings>>,
  TError,
  { data: UpdateEndMarkSettingsCommand },
  TContext
> => {
  const mutationOptions = getUpdateEndMarkSettingsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
