import { useState } from "react";
import { useTranslation } from "react-i18next";
import {
  Box,
  Paper,
  Typography,
  Button,
  Stack,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  CircularProgress,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Chip,
  useTheme,
  alpha,
} from "@mui/material";
import { Print as PrintIcon, Phone as PhoneIcon, Email as EmailIcon } from "@mui/icons-material";
import dayjs from "dayjs";
import { useQuery } from "@tanstack/react-query";
import { executeFetch } from "@api/mutator/executeFetch";

// Types for the Phone List API (will be generated by Orval after backend runs)
type PhoneNumberType = "Mobile" | "Home" | "Work" | "Other";
type GuardianRelationshipType = "Parent" | "Guardian" | "Grandparent" | "Other";

type PhoneListPhoneNumberVM = {
  number: string;
  type: PhoneNumberType;
};

type PhoneListGuardianVM = {
  id: string;
  fullName: string;
  relationshipType: GuardianRelationshipType;
  isPrimaryContact: boolean;
  isEmergencyContact: boolean;
  email?: string | null;
  phoneNumbers: PhoneListPhoneNumberVM[];
};

type PhoneListChildVM = {
  id: string;
  fullName: string;
  dateOfBirth: string;
  childNumber: number;
  guardians: PhoneListGuardianVM[];
};

type PhoneListResponse = {
  year: number;
  generatedAt: string;
  children: PhoneListChildVM[];
};

// Custom hook until Orval regenerates the API client
const useGetPhoneList = (
  params: { year: number },
  options?: { query?: { staleTime?: number; enabled?: boolean } },
) => {
  return useQuery<PhoneListResponse>({
    queryKey: ["/crm/v1/children/phone-list", params],
    queryFn: ({ signal }) =>
      executeFetch<PhoneListResponse>({
        url: `/crm/v1/children/phone-list`,
        method: "GET",
        params,
        signal,
      }),
    staleTime: options?.query?.staleTime,
    enabled: options?.query?.enabled,
  });
};

const currentYear = dayjs().year();
const years = [currentYear - 2, currentYear - 1, currentYear, currentYear + 1, currentYear + 2];

const PrintPhoneListPage = () => {
  const { t } = useTranslation();
  const theme = useTheme();
  const [selectedYear, setSelectedYear] = useState<number>(currentYear);
  const [submitted, setSubmitted] = useState(false);

  const { data, isFetching } = useGetPhoneList(
    { year: selectedYear },
    {
      query: {
        staleTime: 5 * 60 * 1000,
        enabled: submitted,
      },
    },
  );

  const handleGenerate = () => {
    setSubmitted(true);
  };

  const getRelationshipLabel = (type?: string) => {
    switch (type) {
      case "Parent":
        return t("Parent");
      case "Guardian":
        return t("Guardian");
      case "Grandparent":
        return t("Grandparent");
      case "Other":
        return t("Other");
      default:
        return type ?? "";
    }
  };

  const getPhoneTypeLabel = (type?: string) => {
    switch (type) {
      case "Mobile":
        return t("Mobile");
      case "Home":
        return t("Home");
      case "Work":
        return t("Work");
      case "Other":
        return t("Other");
      default:
        return type ?? "";
    }
  };

  const formatPhoneNumber = (number: string) => {
    // Format E.164 phone number for display
    if (number.startsWith("+31")) {
      // Dutch number: +31612345678 -> 06-12345678
      const local = number.slice(3);
      if (local.length === 9 && local.startsWith("6")) {
        return `06-${local.slice(1, 5)} ${local.slice(5)}`;
      }
    }
    return number;
  };

  return (
    <Box sx={{ p: 2 }}>
      {/* Controls - hidden when printing */}
      <Paper sx={{ p: 2, mb: 3 }} className="print-controls">
        <Typography variant="h5" gutterBottom fontWeight={600}>
          {t("Phone List Export")}
        </Typography>
        <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
          {t(
            "Generate a printable phone list of all active children and their guardians for a specific year.",
          )}
        </Typography>
        <Stack direction={{ xs: "column", sm: "row" }} spacing={2} alignItems="center">
          <FormControl sx={{ minWidth: 120 }} size="small">
            <InputLabel id="year-label">{t("Year")}</InputLabel>
            <Select
              labelId="year-label"
              value={selectedYear}
              label={t("Year")}
              onChange={(e) => {
                setSelectedYear(Number(e.target.value));
                setSubmitted(false);
              }}
            >
              {years.map((y) => (
                <MenuItem key={y} value={y}>
                  {y}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          <Stack direction="row" spacing={1}>
            <Button variant="contained" onClick={handleGenerate} disabled={isFetching}>
              {t("Generate")}
            </Button>
            {data && !isFetching && (
              <Button variant="outlined" startIcon={<PrintIcon />} onClick={() => window.print()}>
                {t("Print")}
              </Button>
            )}
          </Stack>
        </Stack>
      </Paper>

      {isFetching && (
        <Box
          sx={{ display: "flex", alignItems: "center", gap: 1, justifyContent: "center", py: 4 }}
        >
          <CircularProgress size={24} />
          <Typography>{t("Loading...")}</Typography>
        </Box>
      )}

      {/* Printable content */}
      {data && !isFetching && (
        <Box className="print-content">
          {/* Print header - visible only when printing */}
          <Box
            className="print-header"
            sx={{
              display: "none",
              "@media print": {
                display: "block",
                mb: 2,
              },
            }}
          >
            <Typography variant="h4" fontWeight="bold" textAlign="center">
              {t("Phone List")} {data.year}
            </Typography>
            <Typography variant="body2" textAlign="center" color="text.secondary">
              {t("Generated on")}: {dayjs(data.generatedAt).format("DD MMMM YYYY HH:mm")}
            </Typography>
          </Box>

          {/* Screen header */}
          <Paper
            className="screen-only"
            sx={{
              p: 2,
              mb: 2,
              background: `linear-gradient(135deg, ${alpha(theme.palette.primary.main, 0.1)}, ${alpha(theme.palette.background.paper, 0.8)})`,
              "@media print": { display: "none" },
            }}
          >
            <Typography variant="h6" fontWeight={600}>
              {t("Phone List")} {data.year}
            </Typography>
            <Typography variant="body2" color="text.secondary">
              {t("Total children")}: {data.children?.length || 0} • {t("Generated on")}:{" "}
              {dayjs(data.generatedAt).format("DD MMMM YYYY HH:mm")}
            </Typography>
          </Paper>

          <TableContainer
            component={Paper}
            className="print-table"
            sx={{
              "@media print": {
                boxShadow: "none",
              },
            }}
          >
            <Table size="small" sx={{ minWidth: 650 }}>
              <TableHead>
                <TableRow>
                  <TableCell sx={{ fontWeight: 600, width: "20%" }}>{t("Child")}</TableCell>
                  <TableCell sx={{ fontWeight: 600, width: "25%" }}>{t("Guardians")}</TableCell>
                  <TableCell sx={{ fontWeight: 600, width: "30%" }}>{t("Phone Numbers")}</TableCell>
                  <TableCell sx={{ fontWeight: 600, width: "25%" }}>{t("Notes")}</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {[...(data.children || [])]
                  .sort((a, b) => a.fullName.localeCompare(b.fullName))
                  .map((child) => {
                    const guardians =
                      child.guardians && child.guardians.length > 0 ? child.guardians : [null];

                    return guardians.map((guardian, gIndex) => (
                      <TableRow
                        key={`${child.id}-${gIndex}`}
                        sx={{
                          "@media print": {
                            pageBreakInside: "avoid",
                          },
                          verticalAlign: "top",
                        }}
                      >
                        {/* Child column */}
                        {gIndex === 0 && (
                          <TableCell rowSpan={guardians.length}>
                            <Box>
                              <Typography variant="body2" fontWeight={600}>
                                {child.fullName}
                              </Typography>
                              <Typography variant="caption" color="text.secondary">
                                {t("DOB")}: {dayjs(child.dateOfBirth).format("DD-MM-YYYY")}
                              </Typography>
                              <br />
                              <Typography variant="caption" color="text.secondary">
                                #{child.childNumber}
                              </Typography>
                            </Box>
                          </TableCell>
                        )}

                        {/* Guardians column */}
                        <TableCell>
                          {guardian ? (
                            <Box>
                              <Typography variant="body2" fontWeight={500}>
                                {guardian.fullName}
                              </Typography>
                              <Stack direction="row" spacing={0.5} flexWrap="wrap" sx={{ mt: 0.5 }}>
                                <Chip
                                  label={getRelationshipLabel(guardian.relationshipType)}
                                  size="small"
                                  variant="outlined"
                                  sx={{ fontSize: "0.65rem", height: 18 }}
                                />
                                {guardian.isEmergencyContact && (
                                  <Chip
                                    label={t("Emergency")}
                                    size="small"
                                    color="error"
                                    sx={{ fontSize: "0.65rem", height: 18 }}
                                  />
                                )}
                              </Stack>
                            </Box>
                          ) : (
                            <Typography variant="body2" color="text.secondary" fontStyle="italic">
                              {t("No guardians linked")}
                            </Typography>
                          )}
                        </TableCell>

                        {/* Phone numbers column */}
                        <TableCell>
                          {guardian ? (
                            <Box>
                              {guardian.phoneNumbers && guardian.phoneNumbers.length > 0 ? (
                                <Stack spacing={0.25}>
                                  {guardian.phoneNumbers.map((phone, idx) => (
                                    <Box
                                      key={idx}
                                      sx={{ display: "flex", alignItems: "center", gap: 0.5 }}
                                    >
                                      <PhoneIcon sx={{ fontSize: 12, color: "text.secondary" }} />
                                      <Typography variant="body2">
                                        {formatPhoneNumber(phone.number)}
                                      </Typography>
                                      <Typography variant="caption" color="text.secondary">
                                        {`(${getPhoneTypeLabel(phone.type)})`}
                                      </Typography>
                                    </Box>
                                  ))}
                                </Stack>
                              ) : (
                                <Typography
                                  variant="body2"
                                  color="text.secondary"
                                  fontStyle="italic"
                                >
                                  {t("No phone")}
                                </Typography>
                              )}
                              {guardian.email && (
                                <Box
                                  sx={{
                                    display: "flex",
                                    alignItems: "center",
                                    gap: 0.5,
                                    mt: 0.25,
                                  }}
                                >
                                  <EmailIcon sx={{ fontSize: 12, color: "text.secondary" }} />
                                  <Typography variant="caption" color="text.secondary">
                                    {guardian.email}
                                  </Typography>
                                </Box>
                              )}
                            </Box>
                          ) : null}
                        </TableCell>

                        {/* Notes column - empty for user to fill in */}
                        {gIndex === 0 && (
                          <TableCell rowSpan={guardians.length}>
                            <Box
                              sx={{
                                minHeight: 40,
                              }}
                            />
                          </TableCell>
                        )}
                      </TableRow>
                    ));
                  })}
              </TableBody>
            </Table>
          </TableContainer>

          {/* Legend */}
          <Box
            sx={{
              mt: 2,
              p: 1,
              display: "flex",
              gap: 2,
              flexWrap: "wrap",
              fontSize: 12,
            }}
            className="print-legend"
          >
            <Box sx={{ display: "flex", alignItems: "center", gap: 0.5 }}>
              <Chip
                label={t("Emergency")}
                size="small"
                color="error"
                sx={{ height: 18, fontSize: "0.65rem" }}
              />
              <Typography variant="caption">{`= ${t("Emergency contact")}`}</Typography>
            </Box>
          </Box>
        </Box>
      )}
    </Box>
  );
};

export const Component = PrintPhoneListPage;

// Print styles
(() => {
  if (typeof document === "undefined") return;
  const existing = document.getElementById("print-phone-list-styles");
  if (existing) return;
  const style = document.createElement("style");
  style.id = "print-phone-list-styles";
  style.innerHTML = `
@media print {
  body { 
    -webkit-print-color-adjust: exact !important; 
    print-color-adjust: exact !important;
    background: #fff; 
  }
  .app-header, header, nav, .MuiAppBar-root, .app-navbar, .app-breadcrumbs, .print-controls { 
    display: none !important; 
  }
  .print-content { 
    padding: 0 !important; 
  }
  .print-table { 
    box-shadow: none !important; 
  }
  .screen-only { 
    display: none !important; 
  }
  .print-header { 
    display: block !important; 
  }
  @page { 
    size: A4 portrait; 
    margin: 10mm 8mm; 
  }
  table { 
    font-size: 9pt !important; 
  }
  .MuiChip-root {
    border: 1px solid #999 !important;
    background: #f5f5f5 !important;
  }
  .MuiChip-colorPrimary {
    background: #e3f2fd !important;
    border-color: #1976d2 !important;
  }
  .MuiChip-colorError {
    background: #ffebee !important;
    border-color: #d32f2f !important;
  }
}`;
  document.head.appendChild(style);
})();
