apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
  namespace: observability
  labels:
    app: clickhouse
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/part-of: observability-stack
    app.kubernetes.io/component: database
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
data:
  remote_servers.xml: |
    <yandex>
        <remote_servers>
            <cluster>
                <shard>
                    <replica>
                        <host>localhost</host>
                        <port>9000</port>
                    </replica>
                </shard>
            </cluster>
        </remote_servers>
    </yandex>
  storage.xml: |
    <yandex>
        <storage_configuration>
            <disks>
                <default>
                    <keep_free_space_bytes>1073741824</keep_free_space_bytes>
                </default>
            </disks>
            <policies>
                <default>
                    <volumes>
                        <default>
                            <disk>default</disk>
                        </default>
                    </volumes>
                </default>
            </policies>
        </storage_configuration>
    </yandex>
