apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - otel-collector-config.yaml
  - otel-collector-deployment.yaml
  - otel-collector-service.yaml
  - otel-collector-rbac.yaml
  # - jaeger-deployment.yaml
  # - jaeger-service.yaml
  # - jaeger-ingress.yaml
  - signoz-application.yaml
  - signoz-ingress.yaml
  # - prometheus-config.yaml
  # - prometheus-deployment.yaml
  # - prometheus-service.yaml
  # - prometheus-rbac.yaml
  # - prometheus-ingress.yaml
  # - auth-secrets.yaml

labels:
- pairs:
    app.kubernetes.io/name: observability-stack
    app.kubernetes.io/part-of: kdvmanager
    app.kubernetes.io/managed-by: kustomize
    environment: production

commonAnnotations:
  argocd.argoproj.io/managed: "true"
