apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-collector-agent
  namespace: observability
  labels:
    app: otel-collector-agent
    app.kubernetes.io/name: otel-collector-agent
    app.kubernetes.io/part-of: observability-stack
    app.kubernetes.io/component: telemetry-agent
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selector:
    matchLabels:
      app: otel-collector-agent
  template:
    metadata:
      labels:
        app: otel-collector-agent
        app.kubernetes.io/name: otel-collector-agent
        app.kubernetes.io/part-of: observability-stack
        app.kubernetes.io/component: telemetry-agent
    spec:
      serviceAccountName: otel-collector
      hostNetwork: false
      containers:
        - name: otel-collector-agent
          image: otel/opentelemetry-collector-contrib:latest
          args: ["--config=/etc/otel-agent-config.yaml"]
          ports:
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: otel-agent-config
              mountPath: /etc/otel-agent-config.yaml
              subPath: otel-agent-config.yaml
          livenessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: otel-agent-config
          configMap:
            name: otel-agent-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-agent-config
  namespace: observability
  labels:
    app: otel-collector-agent
    app.kubernetes.io/name: otel-collector-agent
    app.kubernetes.io/part-of: observability-stack
    app.kubernetes.io/component: telemetry-agent
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  otel-agent-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch:
        timeout: 1s
      memory_limiter:
        limit_mib: 128
        check_interval: 1s
    exporters:
      otlp:
        endpoint: otel-collector.observability.svc.cluster.local:4317
        tls:
          insecure: true
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp]