apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz
  namespace: argocd
  labels:
    app.kubernetes.io/name: signoz
    app.kubernetes.io/part-of: observability-stack
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://charts.signoz.io
    targetRevision: 0.88.2
    chart: signoz
    helm:
      values: |
        global:
          storageClass: do-block-storage
        
        signoz:
          ingress:
            enabled: true
            className: nginx
            hosts:
              - host: signoz.kdvmanager.nl
                paths:
                  - path: /
                    pathType: ImplementationSpecific
                    port: 8080
            tls:
              - secretName: signoz-tls-cert
                hosts:
                  - signoz.kdvmanager.nl
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-production
          env:
            storage: clickhouse
  destination:
    server: https://kubernetes.default.svc
    namespace: signoz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
