/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { useCallback } from "react";
import type { AddTimeSlotCommand } from "../../models/addTimeSlotCommand";
import type { ListTimeSlotsParams } from "../../models/listTimeSlotsParams";
import type { TimeSlotListVM } from "../../models/timeSlotListVM";
import type { UnprocessableEntityResponse } from "../../models/unprocessableEntityResponse";
import { useExecuteFetchPaginated } from "../../mutator/useExecuteFetchPaginated";
import { useExecuteFetch } from "../../mutator/useExecuteFetch";

export const useListTimeSlotsHook = () => {
  const listTimeSlots = useExecuteFetchPaginated<TimeSlotListVM[]>();

  return useCallback(
    (params?: ListTimeSlotsParams, signal?: AbortSignal) => {
      return listTimeSlots({ url: `/scheduling/v1/timeslots`, method: "GET", params, signal });
    },
    [listTimeSlots],
  );
};

export const getListTimeSlotsQueryKey = (params?: ListTimeSlotsParams) => {
  return [`/scheduling/v1/timeslots`, ...(params ? [params] : [])] as const;
};

export const useListTimeSlotsQueryOptions = <
  TData = Awaited<ReturnType<ReturnType<typeof useListTimeSlotsHook>>>,
  TError = unknown,
>(
  params?: ListTimeSlotsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTimeSlotsHook>>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListTimeSlotsQueryKey(params);

  const listTimeSlots = useListTimeSlotsHook();

  const queryFn: QueryFunction<Awaited<ReturnType<ReturnType<typeof useListTimeSlotsHook>>>> = ({
    signal,
  }) => listTimeSlots(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useListTimeSlotsHook>>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListTimeSlotsQueryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useListTimeSlotsHook>>>
>;
export type ListTimeSlotsQueryError = unknown;

export function useListTimeSlots<
  TData = Awaited<ReturnType<ReturnType<typeof useListTimeSlotsHook>>>,
  TError = unknown,
>(
  params: undefined | ListTimeSlotsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTimeSlotsHook>>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListTimeSlotsHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListTimeSlotsHook>>>
        >,
        "initialData"
      >;
  },
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListTimeSlots<
  TData = Awaited<ReturnType<ReturnType<typeof useListTimeSlotsHook>>>,
  TError = unknown,
>(
  params?: ListTimeSlotsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTimeSlotsHook>>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListTimeSlotsHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListTimeSlotsHook>>>
        >,
        "initialData"
      >;
  },
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListTimeSlots<
  TData = Awaited<ReturnType<ReturnType<typeof useListTimeSlotsHook>>>,
  TError = unknown,
>(
  params?: ListTimeSlotsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTimeSlotsHook>>>, TError, TData>
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useListTimeSlots<
  TData = Awaited<ReturnType<ReturnType<typeof useListTimeSlotsHook>>>,
  TError = unknown,
>(
  params?: ListTimeSlotsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<ReturnType<typeof useListTimeSlotsHook>>>, TError, TData>
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = useListTimeSlotsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const useAddTimeSlotHook = () => {
  const addTimeSlot = useExecuteFetch<string>();

  return useCallback(
    (addTimeSlotCommand: AddTimeSlotCommand, signal?: AbortSignal) => {
      return addTimeSlot({
        url: `/scheduling/v1/timeslots`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: addTimeSlotCommand,
        signal,
      });
    },
    [addTimeSlot],
  );
};

export const useAddTimeSlotMutationOptions = <
  TError = UnprocessableEntityResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<ReturnType<typeof useAddTimeSlotHook>>>,
    TError,
    { data: AddTimeSlotCommand },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<ReturnType<typeof useAddTimeSlotHook>>>,
  TError,
  { data: AddTimeSlotCommand },
  TContext
> => {
  const mutationKey = ["addTimeSlot"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const addTimeSlot = useAddTimeSlotHook();

  const mutationFn: MutationFunction<
    Awaited<ReturnType<ReturnType<typeof useAddTimeSlotHook>>>,
    { data: AddTimeSlotCommand }
  > = (props) => {
    const { data } = props ?? {};

    return addTimeSlot(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddTimeSlotMutationResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useAddTimeSlotHook>>>
>;
export type AddTimeSlotMutationBody = AddTimeSlotCommand;
export type AddTimeSlotMutationError = UnprocessableEntityResponse;

export const useAddTimeSlot = <TError = UnprocessableEntityResponse, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<ReturnType<typeof useAddTimeSlotHook>>>,
    TError,
    { data: AddTimeSlotCommand },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<ReturnType<typeof useAddTimeSlotHook>>>,
  TError,
  { data: AddTimeSlotCommand },
  TContext
> => {
  const mutationOptions = useAddTimeSlotMutationOptions(options);

  return useMutation(mutationOptions);
};
