apiVersion: v1
kind: Service
metadata:
  name: childmanagment-api
  namespace: kdvmanager
  labels:
    app: childmanagement-api
    release: production
spec:
  type: NodePort
  selector:
    app: childmanagement-api
    release: production
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31234