/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { AddEndMarkCommand } from "../../models/addEndMarkCommand";

import type { EndMarkDto } from "../../models/endMarkDto";

import type { ListEndMarksParams } from "../../models/listEndMarksParams";

import { executeFetch } from "../../../mutator/executeFetch";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getListEndMarksUrl = (params?: ListEndMarksParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/scheduling/v1/endmarks?${stringifiedParams}`
    : `/scheduling/v1/endmarks`;
};

export const listEndMarks = async (
  params?: ListEndMarksParams,
  options?: RequestInit,
): Promise<EndMarkDto[]> => {
  return executeFetch<EndMarkDto[]>(getListEndMarksUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListEndMarksQueryKey = (params?: ListEndMarksParams) => {
  return [`/scheduling/v1/endmarks`, ...(params ? [params] : [])] as const;
};

export const getListEndMarksQueryOptions = <
  TData = Awaited<ReturnType<typeof listEndMarks>>,
  TError = unknown,
>(
  params?: ListEndMarksParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listEndMarks>>, TError, TData>>;
    request?: SecondParameter<typeof executeFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListEndMarksQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listEndMarks>>> = ({ signal }) =>
    listEndMarks(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listEndMarks>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListEndMarksQueryResult = NonNullable<Awaited<ReturnType<typeof listEndMarks>>>;
export type ListEndMarksQueryError = unknown;

export function useListEndMarks<TData = Awaited<ReturnType<typeof listEndMarks>>, TError = unknown>(
  params: undefined | ListEndMarksParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listEndMarks>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEndMarks>>,
          TError,
          Awaited<ReturnType<typeof listEndMarks>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListEndMarks<TData = Awaited<ReturnType<typeof listEndMarks>>, TError = unknown>(
  params?: ListEndMarksParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listEndMarks>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEndMarks>>,
          TError,
          Awaited<ReturnType<typeof listEndMarks>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListEndMarks<TData = Awaited<ReturnType<typeof listEndMarks>>, TError = unknown>(
  params?: ListEndMarksParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listEndMarks>>, TError, TData>>;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useListEndMarks<TData = Awaited<ReturnType<typeof listEndMarks>>, TError = unknown>(
  params?: ListEndMarksParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listEndMarks>>, TError, TData>>;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListEndMarksQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getAddEndMarkUrl = () => {
  return `/scheduling/v1/endmarks`;
};

export const addEndMark = async (
  addEndMarkCommand?: AddEndMarkCommand,
  options?: RequestInit,
): Promise<void> => {
  return executeFetch<void>(getAddEndMarkUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(addEndMarkCommand),
  });
};

export const getAddEndMarkMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addEndMark>>,
    TError,
    { data?: AddEndMarkCommand },
    TContext
  >;
  request?: SecondParameter<typeof executeFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addEndMark>>,
  TError,
  { data?: AddEndMarkCommand },
  TContext
> => {
  const mutationKey = ["addEndMark"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addEndMark>>,
    { data?: AddEndMarkCommand }
  > = (props) => {
    const { data } = props ?? {};

    return addEndMark(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddEndMarkMutationResult = NonNullable<Awaited<ReturnType<typeof addEndMark>>>;
export type AddEndMarkMutationBody = AddEndMarkCommand | undefined;
export type AddEndMarkMutationError = unknown;

export const useAddEndMark = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addEndMark>>,
      TError,
      { data?: AddEndMarkCommand },
      TContext
    >;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof addEndMark>>,
  TError,
  { data?: AddEndMarkCommand },
  TContext
> => {
  return useMutation(getAddEndMarkMutationOptions(options), queryClient);
};
export const getDeleteEndMarkUrl = (id: string) => {
  return `/scheduling/v1/endmarks/${id}`;
};

export const deleteEndMark = async (id: string, options?: RequestInit): Promise<void> => {
  return executeFetch<void>(getDeleteEndMarkUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteEndMarkMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteEndMark>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof executeFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteEndMark>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteEndMark"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteEndMark>>, { id: string }> = (
    props,
  ) => {
    const { id } = props ?? {};

    return deleteEndMark(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteEndMarkMutationResult = NonNullable<Awaited<ReturnType<typeof deleteEndMark>>>;

export type DeleteEndMarkMutationError = unknown;

export const useDeleteEndMark = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteEndMark>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteEndMark>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteEndMarkMutationOptions(options), queryClient);
};
