apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: kdvmanager-postgres
spec:
   replicas: 1
   image: postgres:14.1
   database:
      size: 1Gi
   env:
      - name: POSTGRES_PASSWORD
        valueFrom:
           secretKeyRef:
              name: kdvmanager-postgres-secret
              key: superUserPassword
      - name: POSTGRES_REPLICATION_PASSWORD
        valueFrom:
           secretKeyRef:
              name: kdvmanager-postgres-secret
              key: replicationUserPassword