apiVersion: v1
kind: Secret
metadata:
  name: kdvmanager-postgres-secret
  labels:
    app: postgres
type: Opaque
stringData:
  superUserPassword: postgresSuperUserPsw
  replicationUserPassword: postgresReplicaPsw
