/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { AddTimeSlotCommand } from "../../models/addTimeSlotCommand";

import type { ListTimeSlotsParams } from "../../models/listTimeSlotsParams";

import type { ProblemDetails } from "../../models/problemDetails";

import type { TimeSlotListVM } from "../../models/timeSlotListVM";

import type { UnprocessableEntityResponse } from "../../models/unprocessableEntityResponse";

import type { UpdateTimeSlotCommand } from "../../models/updateTimeSlotCommand";

import { executeFetchPaginated } from "../../../mutator/executeFetchPaginated";
import { executeFetch } from "../../../mutator/executeFetch";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getListTimeSlotsUrl = (params?: ListTimeSlotsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/scheduling/v1/timeslots?${stringifiedParams}`
    : `/scheduling/v1/timeslots`;
};

export const listTimeSlots = async (
  params?: ListTimeSlotsParams,
  options?: RequestInit,
): Promise<TimeSlotListVM[]> => {
  return executeFetchPaginated<TimeSlotListVM[]>(getListTimeSlotsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListTimeSlotsQueryKey = (params?: ListTimeSlotsParams) => {
  return [`/scheduling/v1/timeslots`, ...(params ? [params] : [])] as const;
};

export const getListTimeSlotsQueryOptions = <
  TData = Awaited<ReturnType<typeof listTimeSlots>>,
  TError = unknown,
>(
  params?: ListTimeSlotsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listTimeSlots>>, TError, TData>>;
    request?: SecondParameter<typeof executeFetchPaginated>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListTimeSlotsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listTimeSlots>>> = ({ signal }) =>
    listTimeSlots(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listTimeSlots>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListTimeSlotsQueryResult = NonNullable<Awaited<ReturnType<typeof listTimeSlots>>>;
export type ListTimeSlotsQueryError = unknown;

export function useListTimeSlots<
  TData = Awaited<ReturnType<typeof listTimeSlots>>,
  TError = unknown,
>(
  params: undefined | ListTimeSlotsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listTimeSlots>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTimeSlots>>,
          TError,
          Awaited<ReturnType<typeof listTimeSlots>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof executeFetchPaginated>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListTimeSlots<
  TData = Awaited<ReturnType<typeof listTimeSlots>>,
  TError = unknown,
>(
  params?: ListTimeSlotsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listTimeSlots>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTimeSlots>>,
          TError,
          Awaited<ReturnType<typeof listTimeSlots>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof executeFetchPaginated>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListTimeSlots<
  TData = Awaited<ReturnType<typeof listTimeSlots>>,
  TError = unknown,
>(
  params?: ListTimeSlotsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listTimeSlots>>, TError, TData>>;
    request?: SecondParameter<typeof executeFetchPaginated>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useListTimeSlots<
  TData = Awaited<ReturnType<typeof listTimeSlots>>,
  TError = unknown,
>(
  params?: ListTimeSlotsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listTimeSlots>>, TError, TData>>;
    request?: SecondParameter<typeof executeFetchPaginated>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListTimeSlotsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getAddTimeSlotUrl = () => {
  return `/scheduling/v1/timeslots`;
};

export const addTimeSlot = async (
  addTimeSlotCommand: AddTimeSlotCommand,
  options?: RequestInit,
): Promise<string> => {
  return executeFetch<string>(getAddTimeSlotUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(addTimeSlotCommand),
  });
};

export const getAddTimeSlotMutationOptions = <
  TError = UnprocessableEntityResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addTimeSlot>>,
    TError,
    { data: AddTimeSlotCommand },
    TContext
  >;
  request?: SecondParameter<typeof executeFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addTimeSlot>>,
  TError,
  { data: AddTimeSlotCommand },
  TContext
> => {
  const mutationKey = ["addTimeSlot"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addTimeSlot>>,
    { data: AddTimeSlotCommand }
  > = (props) => {
    const { data } = props ?? {};

    return addTimeSlot(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddTimeSlotMutationResult = NonNullable<Awaited<ReturnType<typeof addTimeSlot>>>;
export type AddTimeSlotMutationBody = AddTimeSlotCommand;
export type AddTimeSlotMutationError = UnprocessableEntityResponse;

export const useAddTimeSlot = <TError = UnprocessableEntityResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addTimeSlot>>,
      TError,
      { data: AddTimeSlotCommand },
      TContext
    >;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof addTimeSlot>>,
  TError,
  { data: AddTimeSlotCommand },
  TContext
> => {
  return useMutation(getAddTimeSlotMutationOptions(options), queryClient);
};
export const getUpdateTimeSlotUrl = (id: string) => {
  return `/scheduling/v1/timeslots/${id}`;
};

export const updateTimeSlot = async (
  id: string,
  updateTimeSlotCommand: UpdateTimeSlotCommand,
  options?: RequestInit,
): Promise<void> => {
  return executeFetch<void>(getUpdateTimeSlotUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateTimeSlotCommand),
  });
};

export const getUpdateTimeSlotMutationOptions = <
  TError = ProblemDetails | UnprocessableEntityResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateTimeSlot>>,
    TError,
    { id: string; data: UpdateTimeSlotCommand },
    TContext
  >;
  request?: SecondParameter<typeof executeFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateTimeSlot>>,
  TError,
  { id: string; data: UpdateTimeSlotCommand },
  TContext
> => {
  const mutationKey = ["updateTimeSlot"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateTimeSlot>>,
    { id: string; data: UpdateTimeSlotCommand }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateTimeSlot(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateTimeSlotMutationResult = NonNullable<Awaited<ReturnType<typeof updateTimeSlot>>>;
export type UpdateTimeSlotMutationBody = UpdateTimeSlotCommand;
export type UpdateTimeSlotMutationError = ProblemDetails | UnprocessableEntityResponse;

export const useUpdateTimeSlot = <
  TError = ProblemDetails | UnprocessableEntityResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateTimeSlot>>,
      TError,
      { id: string; data: UpdateTimeSlotCommand },
      TContext
    >;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateTimeSlot>>,
  TError,
  { id: string; data: UpdateTimeSlotCommand },
  TContext
> => {
  return useMutation(getUpdateTimeSlotMutationOptions(options), queryClient);
};
export const getDeleteTimeSlotUrl = (id: string) => {
  return `/scheduling/v1/timeslots/${id}`;
};

export const deleteTimeSlot = async (id: string, options?: RequestInit): Promise<void> => {
  return executeFetch<void>(getDeleteTimeSlotUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteTimeSlotMutationOptions = <
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteTimeSlot>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof executeFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteTimeSlot>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteTimeSlot"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTimeSlot>>, { id: string }> = (
    props,
  ) => {
    const { id } = props ?? {};

    return deleteTimeSlot(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteTimeSlotMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTimeSlot>>>;

export type DeleteTimeSlotMutationError = ProblemDetails;

export const useDeleteTimeSlot = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteTimeSlot>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteTimeSlot>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteTimeSlotMutationOptions(options), queryClient);
};
