/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */

export type AddClosurePeriodCommand = {
  startDate?: string;
  endDate?: string;
  /** @nullable */
  reason?: string | null;
};
