/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import type { AddPhoneNumberDto } from "./addPhoneNumberDto";

export type AddGuardianCommand = {
  givenName?: string;
  familyName?: string;
  dateOfBirth?: string;
  email?: string;
  phoneNumbers?: AddPhoneNumberDto[];
};
