/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */

export interface AddPersonCommand {
  givenName?: string | null;
  familyName?: string | null;
  dateOfBirth?: string;
  email?: string | null;
  bsn?: string | null;
  phoneNumber?: string | null;
}
