/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */

export type AddPersonCommand = {
  /** @nullable */
  bsn?: string | null;
  dateOfBirth?: string;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  familyName?: string | null;
  /** @nullable */
  givenName?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
};
