/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import type { AddScheduleCommandScheduleRule } from "./addScheduleCommandScheduleRule";

export type AddScheduleCommand = {
  childId?: string;
  startDate?: string;
  /** @nullable */
  endDate?: string | null;
  /** @nullable */
  scheduleRules?: AddScheduleCommandScheduleRule[] | null;
};
