/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import type { DayOfWeek } from "./dayOfWeek";

export type AddScheduleCommandScheduleRule = {
  day?: DayOfWeek;
  timeSlotId?: string;
};
