/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */

export type AddScheduleItemCommand = {
  childId?: string;
  /** @nullable */
  name?: string | null;
};
