/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */

export type AgeAddOptionVM = {
  /** @nullable */
  ageRange?: string | null;
  canAddWithCurrentStaff?: boolean;
  canAddWithOneExtraStaff?: boolean;
  additionalProfessionalsNeeded?: number;
  resultingProfessionals?: number;
};
