/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import type { AttendanceScheduleVM } from "./attendanceScheduleVM";

export type AttendanceChildVM = {
  childId?: string;
  /** @nullable */
  fullName?: string | null;
  dateOfBirth?: string;
  age?: number;
  beginTime?: string;
  endTime?: string;
  /** @nullable */
  schedules?: AttendanceScheduleVM[] | null;
};
