/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import type { AttendanceChildVM } from "./attendanceChildVM";

export type AttendanceListVM = {
  /** @nullable */
  groupName?: string | null;
  /** @nullable */
  dayName?: string | null;
  /** @nullable */
  monthName?: string | null;
  year?: number;
  month?: number;
  dayOfWeek?: number;
  /** @nullable */
  dates?: string[] | null;
  /** @nullable */
  children?: AttendanceChildVM[] | null;
  isEmpty?: boolean;
};
