/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */

export type AttendanceScheduleVM = {
  date?: string;
  isScheduled?: boolean;
  /** @nullable */
  beginTime?: string | null;
  /** @nullable */
  endTime?: string | null;
};
