/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */

export type ChildDetailVM = {
  id?: string;
  /** @nullable */
  givenName?: string | null;
  /** @nullable */
  familyName?: string | null;
  /** @nullable */
  dateOfBirth?: string | null;
  /** @nullable */
  cid?: string | null;
};
