/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * KDVManager.Services.CRM.Api
 * OpenAPI spec version: 1.0
 */

export interface ChildListVM {
  id?: string;
  fullName?: string | null;
  dateOfBirth?: string;
}
