/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */

export type ChildDetailVM = {
  /** @nullable */
  dateOfBirth?: string | null;
  /** @nullable */
  familyName?: string | null;
  /** @nullable */
  givenName?: string | null;
  id?: string;
};
