/**
 * Generated by orval v6.13.1 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */

export interface ChildListVM {
  id?: string;
  fullName?: string | null;
  dateOfBirth?: string;
}
