/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */

export type ChildListVM = {
  /** @nullable */
  dateOfBirth?: string | null;
  /** @nullable */
  fullName?: string | null;
  id?: string;
};
