/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */

export interface CreateChildCommand {
  familyName?: string | null;
  givenName?: string | null;
}
