/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */

export interface CreateChildCommand {
  givenName?: string | null;
  familyName?: string | null;
}
