/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */

export type CreateChildCommand = {
  /** @nullable */
  dateOfBirth?: string | null;
  /** @nullable */
  familyName?: string | null;
  /** @nullable */
  givenName?: string | null;
};
