/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import type { GroupDailyOverviewVM } from "./groupDailyOverviewVM";

export type DailyOverviewVM = {
  date?: string;
  isClosed?: boolean;
  /** @nullable */
  closureReason?: string | null;
  /** @nullable */
  groups?: GroupDailyOverviewVM[] | null;
};
