/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */

export type EndMarkSettingsDto = {
  isEnabled?: boolean;
  yearsAfterBirth?: number;
  /** @nullable */
  description?: string | null;
};
