/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */

export type EndMarkDto = {
  id?: string;
  endDate?: string;
  /** @nullable */
  reason?: string | null;
};
