/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */

export type GetAttendanceListParams = {
  year?: number;
  month?: number;
  dayOfWeek?: number;
  groupId?: number;
};
