/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */

export type GroupListVM = {
  id?: string;
  /** @nullable */
  name?: string | null;
};
