/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import type { ChildScheduleDailyVM } from "./childScheduleDailyVM";

export type GroupDailyOverviewVM = {
  groupId?: string;
  /** @nullable */
  groupName?: string | null;
  /** @nullable */
  schedules?: ChildScheduleDailyVM[] | null;
};
