/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * KDVManager.Services.ChildManagement.Api
 * OpenAPI spec version: 1.0
 */

export interface GroupListVM {
  id?: string;
  name?: string;
}
