/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */

export type GuardianRelationshipType =
  (typeof GuardianRelationshipType)[keyof typeof GuardianRelationshipType];

export const GuardianRelationshipType = {
  Parent: "Parent",
  Guardian: "Guardian",
  Grandparent: "Grandparent",
  Other: "Other",
} as const;
