/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import type { GuardianRelationshipType } from "./guardianRelationshipType";

export type GuardianChildVM = {
  childId?: string;
  fullName: string;
  /** @nullable */
  cid?: string | null;
  dateOfBirth?: string;
  age?: number;
  relationshipType?: GuardianRelationshipType;
  isPrimaryContact?: boolean;
  isEmergencyContact?: boolean;
};
