/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import type { PhoneNumberVM } from "./phoneNumberVM";
import type { ChildRelationshipVM } from "./childRelationshipVM";

export type GuardianDetailVM = {
  id?: string;
  givenName: string;
  familyName: string;
  /** @nullable */
  dateOfBirth?: string | null;
  /** @nullable */
  email?: string | null;
  phoneNumbers?: PhoneNumberVM[];
  children?: ChildRelationshipVM[];
};
