/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */

export type ListGuardiansParams = {
  search?: string;
  pageNumber: number;
  pageSize: number;
};
