/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import type { PlanningDayVM } from "./planningDayVM";

export type LongTermPlanningVM = {
  startDate: string;
  days: number;
  /** @nullable */
  daysData: PlanningDayVM[] | null;
};
