/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */

export interface PersonListVM {
  bsn?: string | null;
  dateOfBirth?: string;
  email?: string | null;
  fullName?: string | null;
  id?: string;
  phoneNumber?: string | null;
}
