/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */

export type PersonListVM = {
  /** @nullable */
  bsn?: string | null;
  dateOfBirth?: string;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  fullName?: string | null;
  id?: string;
  /** @nullable */
  phoneNumber?: string | null;
};
