/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import type { PhoneNumberType } from "./phoneNumberType";

export type PhoneNumberVM = {
  id?: string;
  number?: string;
  type?: PhoneNumberType;
};
