/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import type { GuardianRelationshipType } from "./guardianRelationshipType";
import type { PhoneListPhoneNumberVM } from "./phoneListPhoneNumberVM";

export type PhoneListGuardianVM = {
  id: string;
  fullName: string;
  relationshipType: GuardianRelationshipType;
  isPrimaryContact: boolean;
  isEmergencyContact: boolean;
  /** @nullable */
  email?: string | null;
  phoneNumbers: PhoneListPhoneNumberVM[];
};
