/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import type { AgeGroupSummary } from "./ageGroupSummary";
import type { AgeAddOptionVM } from "./ageAddOptionVM";

export type PlanningTimeBlockVM = {
  startTime: string;
  endTime: string;
  /** @nullable */
  timeSlotName: string | null;
  totalChildren: number;
  requiredProfessionals: number;
  capacityCurrent?: number;
  capacityWithExtraSupervisor?: number;
  readonly spotsCurrent?: number;
  readonly spotsWithExtraSupervisor?: number;
  originalHasSolution?: boolean;
  /** @nullable */
  ageGroups?: AgeGroupSummary[] | null;
  /** @nullable */
  ageAddOptions?: AgeAddOptionVM[] | null;
};
