/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */

export type PrintCellVM = {
  /** @nullable */
  status?: string | null;
  /** @nullable */
  absenceType?: string | null;
  /** @nullable */
  startTime?: string | null;
  /** @nullable */
  endTime?: string | null;
};
