/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import type { PrintChildVMSchedule } from "./printChildVMSchedule";

export type PrintChildVM = {
  id?: string;
  /** @nullable */
  givenName?: string | null;
  /** @nullable */
  familyName?: string | null;
  /** @nullable */
  dateOfBirth?: string | null;
  /** @nullable */
  schedule?: PrintChildVMSchedule;
  index?: number;
  /** @nullable */
  ageDisplay?: string | null;
  /** @nullable */
  readonly name?: string | null;
};
