/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */

export type ScheduleByDateVM = {
  scheduleId?: string;
  childId?: string;
  /** @nullable */
  childFullName?: string | null;
  /** @nullable */
  timeSlotName?: string | null;
  startTime?: string;
  endTime?: string;
};
