/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */

export type ScheduleItemListVM = {
  childId?: string;
  /** @nullable */
  endDate?: string | null;
  id?: string;
  startDate?: string;
};
