/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import type { DayOfWeek } from "./dayOfWeek";

export type Schedule = {
  day?: DayOfWeek;
};
