/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import type { AgeGroupSummary } from "./ageGroupSummary";

export type TimeBlockSummary = {
  startTime: string;
  endTime: string;
  /** @nullable */
  timeSlotName: string | null;
  totalChildren: number;
  requiredProfessionals: number;
  /** @nullable */
  ageGroups: AgeGroupSummary[] | null;
};
