/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import type { ValidationError } from "./validationError";

export type UnprocessableEntityResponse = {
  errors: ValidationError[];
  status: number;
};
