/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import type { ValidationError1 } from "./validationError1";

export type UnprocessableEntityResponse1 = {
  status: number;
  errors: ValidationError1[];
};
