/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */

export type UpdateChildCommand = {
  id: string;
  /** @nullable */
  givenName: string | null;
  /** @nullable */
  familyName: string | null;
  /** @nullable */
  dateOfBirth: string | null;
  /** @nullable */
  cid?: string | null;
};
