/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */

export interface ValidationError {
  code: string;
  property: string;
  title: string;
}
