/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */

export type ValidationError = {
  code: string;
  property: string;
  title: string;
};
