apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4
          imagePullPolicy: Always
          ports:
            - name: tcp
              containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: raj@nola.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: admin
