import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";
import type { FlatConfig } from "@typescript-eslint/utils/ts-eslint";
import { globalIgnores } from "eslint/config";
import react from "eslint-plugin-react";
import i18next from "eslint-plugin-i18next";

const config: FlatConfig.ConfigArray = tseslint.config([
  globalIgnores([
    "dist",
    "eslint.config.ts",
    "i18next-parser.config.ts",
    "orval.config.ts",
    "knip.config.ts",
  ]),
  {
    files: ["**/*.{ts,tsx}"],
    plugins: {
      react,
    },
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      tseslint.configs.strict,
      tseslint.configs.stylisticTypeChecked,
      reactHooks.configs["recommended-latest"],
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
      parserOptions: {
        project: "./tsconfig.app.json",
        tsconfigRootDir: __dirname,
      },
    },
    rules: {
      // Common rules from your previous config
      "no-multiple-empty-lines": ["error", { max: 1, maxBOF: 1 }],
      "@typescript-eslint/consistent-type-imports": ["error", { fixStyle: "inline-type-imports" }],
      "@typescript-eslint/consistent-type-definitions": ["error", "type"],
      "@typescript-eslint/no-non-null-assertion": "off",
      "@typescript-eslint/no-explicit-any": "off",
      "no-restricted-imports": ["error", { patterns: ["@mui/*/*/*"] }],
    },
  },
  {
    files: ["**/*.{ts,tsx}"],
    plugins: {
      i18next,
    },
    rules: {
      "i18next/no-literal-string": [
        "error",
        {
          mode: "all",
          "jsx-attributes": {
            include: [
              "label",
              "alt",
              "title",
              "placeholder",
              "aria-description",
              "aria-label",
              "aria-placeholder",
              "rules",
            ],
            exclude: [],
          },
          "jsx-components": {
            include: [],
            exclude: ["Trans"],
          },
          callees: {
            exclude: [
              "i18n",
              "t",
              "require",
              "addEventListener",
              "removeEventListener",
              "postMessage",
              "getElementById",
              "dispatch",
              "commit",
              "includes",
              "indexOf",
              "endsWith",
              "startsWith",
              "navigate",
              "toLocaleDateString",
              "toLocaleString",
              "format",
              "console.log",
              "console.error",
              "console.warn",
              "console.info",
            ],
          },
          "object-properties": {
            include: ["required", "message", "error", "headerName"],
            exclude: [],
          },
          words: {
            exclude: [
              "\\.\\.\\.",
              "•",
              "#",
              ":",
              " • ",
              " : ",
              " - ",
              "—",
              "–",
              "application/json",
              "text/plain",
              "_blank",
              "_self",
              "_parent",
              "_top",
              "GET",
              "POST",
              "PUT",
              "DELETE",
              "PATCH",
              "HEAD",
              "OPTIONS",
              "utf-8",
              "UTF-8",
              "en",
              "en-US",
              "nl",
              "rgba",
              "rgb",
              "#[0-9a-fA-F]+",
              "px",
              "rem",
              "em",
              "%",
              "vh",
              "vw",
              "auto",
              "none",
              "hidden",
              "visible",
              "flex",
              "block",
              "inline",
              "absolute",
              "relative",
              "fixed",
              "sticky",
              "center",
              "left",
              "right",
              "top",
              "bottom",
              "error",
              "warning",
              "info",
              "success",
              "md",
              "sm",
              "lg",
              "xl",
              "xs",
              "\\?",
              "→",
              "[A-Z]",
              "\\d{2}:\\d{2}",
              "YYYY-MM-DD",
              "DD MMM",
              "DD MMM YYYY",
              "[\\+\\-]?\\d+",
              "page",
              "size",
              "q",
              "date",
              "returnTo",
              "/schedule",
              "content-type",
              "auth_app_state",
              "\\.[a-zA-Z]+",
              "addAbsence",
              "deleteAbsence",
              "addChild",
              "updateChild",
              "deleteChild",
              "addClosurePeriod",
              "deleteClosurePeriod",
              "addEndMark",
              "deleteEndMark",
              "addGroup",
              "deleteGroup",
              "addGuardian",
              "updateGuardian",
              "deleteGuardian",
              "linkGuardianToChild",
              "unlinkGuardianFromChild",
              "addSchedule",
              "deleteSchedule",
              "addTimeSlot",
              "deleteTimeSlot",
            ],
          },
          object: {
            include: ["headerName"],
            exclude: [
              "style",
              "className",
              "sx",
              "variant",
              "color",
              "size",
              "type",
              "role",
              "method",
              "encType",
              "target",
              "rel",
              "download",
            ],
          },
        },
      ],
    },
  },
  {
    files: ["src/api/endpoints/**/*.{ts,tsx}"],
    rules: {
      "i18next/no-literal-string": "off",
      "@typescript-eslint/no-invalid-void-type": "off",
      "@typescript-eslint/unified-signatures": "off",
    },
  },
]);

export default config;
