import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";
import { playwright } from "@vitest/browser-playwright";
import path from "node:path";

const r = (p: string) => path.resolve(__dirname, p);

/**
 * Vitest config — runs all tests in a real Chromium via Playwright using
 * Vitest's browser mode.
 *
 * Why browser mode (vs. happy-dom):
 * - Real CSS layout, focus, transitions and ARIA semantics — the way the
 *   app actually behaves in production.
 * - Native CDP-driven `userEvent` (from `@vitest/browser/context`) is much
 *   faster and more reliable than the simulated JSDOM/happy-dom variants
 *   for popovers, date pickers, drag-and-drop, etc.
 * - Locator-based queries (`page.getByRole(...)`) auto-retry until the
 *   element is visible, removing the `getBy*` vs `findBy*` split.
 *
 * Requires the Chromium binary:
 *   pnpm exec playwright install chromium
 */
export default defineConfig({
  cacheDir: "./node_modules/.cache/vitest",
  plugins: [
    react({
      jsxImportSource: "@emotion/react",
    }),
  ],
  resolve: {
    alias: {
      "@api": r("./src/api"),
      "@hooks": r("./src/hooks"),
      "@lib": r("./src/lib"),
      "@providers": r("./src/providers"),
      "@pages": r("./src/pages"),
      "@components": r("./src/components"),
      "@features": r("./src/features"),
      "@utils": r("./src/utils"),
    },
  },
  test: {
    globals: false,
    include: ["src/**/*.{test,spec}.{ts,tsx}"],
    exclude: ["node_modules", "dist", ".idea", ".git", ".cache", "src/api/**"],
    setupFiles: ["./src/test/setup.matchers.ts", "./src/test/setup.i18n.ts"],

    // Browser mode isolates at the iframe/page level; skipping per-test
    // module isolation keeps the dev-server module graph hot between tests.
    isolate: false,

    // Hygiene --------------------------------------------------------------
    restoreMocks: true,
    clearMocks: true,
    mockReset: true,
    unstubGlobals: true,
    unstubEnvs: true,

    // Reporting / CI -------------------------------------------------------
    reporters: process.env.CI ? ["dot", "github-actions"] : ["default"],

    // Browser --------------------------------------------------------------
    browser: {
      enabled: true,
      provider: playwright(),
      headless: true,
      instances: [{ browser: "chromium" }],
      ui: false,
      screenshotFailures: true,
    },

    // Coverage -------------------------------------------------------------
    coverage: {
      provider: "v8",
      reporter: ["text", "html", "lcov"],
      reportsDirectory: "./coverage",
      include: ["src/**/*.{ts,tsx}"],
      exclude: [
        "src/**/*.{test,spec}.{ts,tsx}",
        "src/test/**",
        "src/api/**", // generated by Orval
        "src/**/*.d.ts",
        "src/index.tsx",
        "src/vite-env.d.ts",
      ],
    },
  },
});
