import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";
import { playwright } from "@vitest/browser-playwright";
import path from "node:path";

const r = (p: string) => path.resolve(__dirname, p);

/**
 * Vitest config — runs all tests in a real Chromium via Playwright using
 * Vitest's browser mode.
 *
 * Why browser mode (vs. happy-dom):
 * - Real CSS layout, focus, transitions and ARIA semantics — the way the
 *   app actually behaves in production.
 * - Native CDP-driven `userEvent` (from `@vitest/browser/context`) is much
 *   faster and more reliable than the simulated JSDOM/happy-dom variants
 *   for popovers, date pickers, drag-and-drop, etc.
 * - Locator-based queries (`page.getByRole(...)`) auto-retry until the
 *   element is visible, removing the `getBy*` vs `findBy*` split.
 *
 * Requires the Chromium binary:
 *   pnpm exec playwright install chromium
 */
export default defineConfig({
  cacheDir: "./node_modules/.cache/vitest",
  plugins: [
    react({
      jsxImportSource: "@emotion/react",
    }),
  ],
  optimizeDeps: {
    // Crawl every test file and the app entry up front so all dependencies are
    // pre-bundled before tests start. Otherwise, on a cold cache (CI) vite
    // discovers deps reached through dynamic imports mid-run, and the re-bundle
    // reloads the test page — which can swallow an in-flight interaction (seen
    // as a tapped card that never navigates). Debug with `DEBUG=vite:deps`:
    // "new dependencies found" during the run means this list has a gap.
    entries: ["src/**/*.{test,spec}.{ts,tsx}", "src/test/*.{ts,tsx}", "src/index.tsx"],
  },
  resolve: {
    alias: {
      "@api": r("./src/api"),
      "@hooks": r("./src/hooks"),
      "@lib": r("./src/lib"),
      "@providers": r("./src/providers"),
      "@pages": r("./src/pages"),
      "@components": r("./src/components"),
      "@features": r("./src/features"),
      "@utils": r("./src/utils"),
    },
  },
  test: {
    globals: false,
    include: ["src/**/*.{test,spec}.{ts,tsx}"],
    exclude: ["node_modules", "dist", ".idea", ".git", ".cache", "src/api/**"],
    setupFiles: ["./src/test/setup.matchers.ts", "./src/test/setup.i18n.ts"],

    // Per-file isolation is required for correctness: with `isolate: false`
    // the module graph is shared across test files, so vi.mock factories leak
    // between files (a later file importing the real module gets another
    // file's partial mock) and module-scope lifecycle hooks only bind to the
    // first importing file (vitest-browser-react's auto-cleanup stopped
    // running, leaking mounted trees and dialog backdrops into later tests).
    // Reproduce the breakage with: rm -rf node_modules/.cache/vitest &&
    // taskset -c 0,1 pnpm vitest run (2-core pinning matches CI runners).
    isolate: true,

    // Hygiene --------------------------------------------------------------
    restoreMocks: true,
    clearMocks: true,
    mockReset: true,
    unstubGlobals: true,
    unstubEnvs: true,

    // Reporting / CI -------------------------------------------------------
    reporters: process.env.CI ? ["dot", "github-actions"] : ["default"],

    // Browser --------------------------------------------------------------
    browser: {
      enabled: true,
      provider: playwright(),
      headless: true,
      instances: [{ browser: "chromium" }],
      ui: false,
      screenshotFailures: true,
    },

    // Coverage -------------------------------------------------------------
    coverage: {
      provider: "v8",
      reporter: ["text", "html", "lcov"],
      reportsDirectory: "./coverage",
      include: ["src/**/*.{ts,tsx}"],
      exclude: [
        "src/**/*.{test,spec}.{ts,tsx}",
        "src/test/**",
        "src/api/**", // generated by Orval
        "src/**/*.d.ts",
        "src/index.tsx",
        "src/vite-env.d.ts",
      ],
    },
  },
});
