/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { AddEndMarkCommand } from "../../models/addEndMarkCommand";

import type { EndMarkDto } from "../../models/endMarkDto";

import type { ListEndMarksParams } from "../../models/listEndMarksParams";

import { executeFetch } from "../../mutator/executeFetch";

export const listEndMarks = (params?: ListEndMarksParams, signal?: AbortSignal) => {
  return executeFetch<EndMarkDto[]>({
    url: `/scheduling/v1/endmarks`,
    method: "GET",
    params,
    signal,
  });
};

export const getListEndMarksQueryKey = (params?: ListEndMarksParams) => {
  return [`/scheduling/v1/endmarks`, ...(params ? [params] : [])] as const;
};

export const getListEndMarksQueryOptions = <
  TData = Awaited<ReturnType<typeof listEndMarks>>,
  TError = unknown,
>(
  params?: ListEndMarksParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listEndMarks>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListEndMarksQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listEndMarks>>> = ({ signal }) =>
    listEndMarks(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listEndMarks>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListEndMarksQueryResult = NonNullable<Awaited<ReturnType<typeof listEndMarks>>>;
export type ListEndMarksQueryError = unknown;

export function useListEndMarks<TData = Awaited<ReturnType<typeof listEndMarks>>, TError = unknown>(
  params: undefined | ListEndMarksParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listEndMarks>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEndMarks>>,
          TError,
          Awaited<ReturnType<typeof listEndMarks>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListEndMarks<TData = Awaited<ReturnType<typeof listEndMarks>>, TError = unknown>(
  params?: ListEndMarksParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listEndMarks>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEndMarks>>,
          TError,
          Awaited<ReturnType<typeof listEndMarks>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListEndMarks<TData = Awaited<ReturnType<typeof listEndMarks>>, TError = unknown>(
  params?: ListEndMarksParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listEndMarks>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useListEndMarks<TData = Awaited<ReturnType<typeof listEndMarks>>, TError = unknown>(
  params?: ListEndMarksParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listEndMarks>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListEndMarksQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const addEndMark = (addEndMarkCommand: AddEndMarkCommand, signal?: AbortSignal) => {
  return executeFetch<void>({
    url: `/scheduling/v1/endmarks`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: addEndMarkCommand,
    signal,
  });
};

export const getAddEndMarkMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addEndMark>>,
    TError,
    { data: AddEndMarkCommand },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addEndMark>>,
  TError,
  { data: AddEndMarkCommand },
  TContext
> => {
  const mutationKey = ["addEndMark"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addEndMark>>,
    { data: AddEndMarkCommand }
  > = (props) => {
    const { data } = props ?? {};

    return addEndMark(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddEndMarkMutationResult = NonNullable<Awaited<ReturnType<typeof addEndMark>>>;
export type AddEndMarkMutationBody = AddEndMarkCommand;
export type AddEndMarkMutationError = unknown;

export const useAddEndMark = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addEndMark>>,
      TError,
      { data: AddEndMarkCommand },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof addEndMark>>,
  TError,
  { data: AddEndMarkCommand },
  TContext
> => {
  const mutationOptions = getAddEndMarkMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const deleteEndMark = (id: string) => {
  return executeFetch<void>({ url: `/scheduling/v1/endmarks/${id}`, method: "DELETE" });
};

export const getDeleteEndMarkMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteEndMark>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteEndMark>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteEndMark"];
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteEndMark>>, { id: string }> = (
    props,
  ) => {
    const { id } = props ?? {};

    return deleteEndMark(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteEndMarkMutationResult = NonNullable<Awaited<ReturnType<typeof deleteEndMark>>>;

export type DeleteEndMarkMutationError = unknown;

export const useDeleteEndMark = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteEndMark>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteEndMark>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteEndMarkMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
