version: '3.4'

services:
  envoy:
    image: envoyproxy/envoy:v1.34.0
    command: ["/usr/local/bin/envoy", "-c", "/etc/envoy/envoy.yaml", "--log-level", "info"]
    volumes:
      - ./Services/ApiGateways/Envoy/config/envoy.yaml:/etc/envoy/envoy.yaml:ro
    ports:
      - "8080:8080"
      - "8001:8001"

  postgres:
    image: postgres:latest

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    image: ${REGISTRY:-kdvmanager}/web:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: ./web
      args:
        VITE_APP_AUTH0_DOMAIN: kdvmanager.eu.auth0.com
        VITE_APP_AUTH0_CLIENT_ID: ITepsevBBZNElNNrVmZjgkwaVCsmmKWc
        VITE_API_BASE_URL: https://api.kdvmanager.nl

  crm-api:
    image: ${REGISTRY:-kdvmanager}/crm.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/CRM/Api/Dockerfile
    depends_on:
      - postgres
      - rabbitmq

  crm-migrator:
    image: ${REGISTRY:-kdvmanager}/crm.migrator:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/CRM/Infrastructure/Dockerfile
    depends_on:
      - postgres

  scheduling-api:
    image: ${REGISTRY:-kdvmanager}/scheduling.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Scheduling/Api/Dockerfile
    depends_on:
      - postgres
      - rabbitmq

  scheduling-migrator:
    image: ${REGISTRY:-kdvmanager}/scheduling.migrator:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Scheduling/Infrastructure/Dockerfile
    depends_on:
      - postgres

  data-migration:
    image: ${REGISTRY:-kdvmanager}/data.migration:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/DataMigration/Dockerfile
    depends_on:
      - postgres
