version: '3.4'

services:
  envoy:
    image: envoyproxy/envoy:v1.24.1

  postgres:
    image: postgres:latest

  childmanagement-api:
    image: ${REGISTRY:-kdvmanager}/childmanagement.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/ChildManagement/Api/Dockerfile
    depends_on:
      - postgres

  childmanagement-migrator:
    image: ${REGISTRY:-kdvmanager}/childmanagement.migrator:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/ChildManagement/Infrastructure/Dockerfile
    depends_on:
      - postgres

  scheduling-api:
    image: ${REGISTRY:-kdvmanager}/scheduling.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Scheduling/Api/Dockerfile
    depends_on:
      - postgres

  scheduling-migrator:
    image: ${REGISTRY:-kdvmanager}/scheduling.migrator:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Scheduling/Infrastructure/Dockerfile
    depends_on:
      - postgres
