version: '3.4'

services:
  envoy:
    image: envoyproxy/envoy:v1.24.1
    command: ["/usr/local/bin/envoy", "-c", "/etc/envoy/envoy.yaml", "--log-level", "info"]
    volumes:
      - ./Services/ApiGateways/Envoy/config/envoy.yaml:/etc/envoy/envoy.yaml:ro
    ports:
      - "8080:8080"
      - "8001:8001"

  postgres:
    image: postgres:latest

  web:
    image: ${REGISTRY:-kdvmanager}/web:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: ./web
      cache_from:
        - ${REGISTRY:-kdvmanager}/web:${PLATFORM:-linux}-${TAG:-latest}
        - node:22-slim
      args:
        VITE_APP_AUTH0_DOMAIN: kdvmanager.eu.auth0.com
        VITE_APP_AUTH0_CLIENT_ID: ITepsevBBZNElNNrVmZjgkwaVCsmmKWc
        VITE_API_BASE_URL: https://api.kdvmanager.nl

  crm-api:
    image: ${REGISTRY:-kdvmanager}/crm.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/CRM/Api/Dockerfile
      cache_from:
        - ${REGISTRY:-kdvmanager}/crm.api:${PLATFORM:-linux}-${TAG:-latest}
        - mcr.microsoft.com/dotnet/aspnet:9.0
        - mcr.microsoft.com/dotnet/sdk:9.0
    depends_on:
      - postgres

  crm-migrator:
    image: ${REGISTRY:-kdvmanager}/crm.migrator:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/CRM/Infrastructure/Dockerfile
      cache_from:
        - ${REGISTRY:-kdvmanager}/crm.migrator:${PLATFORM:-linux}-${TAG:-latest}
        - mcr.microsoft.com/dotnet/aspnet:9.0
        - mcr.microsoft.com/dotnet/sdk:9.0
    depends_on:
      - postgres

  scheduling-api:
    image: ${REGISTRY:-kdvmanager}/scheduling.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Scheduling/Api/Dockerfile
      cache_from:
        - ${REGISTRY:-kdvmanager}/scheduling.api:${PLATFORM:-linux}-${TAG:-latest}
        - mcr.microsoft.com/dotnet/aspnet:9.0
        - mcr.microsoft.com/dotnet/sdk:9.0
    depends_on:
      - postgres

  scheduling-migrator:
    image: ${REGISTRY:-kdvmanager}/scheduling.migrator:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Scheduling/Infrastructure/Dockerfile
      cache_from:
        - ${REGISTRY:-kdvmanager}/scheduling.migrator:${PLATFORM:-linux}-${TAG:-latest}
        - mcr.microsoft.com/dotnet/aspnet:9.0
        - mcr.microsoft.com/dotnet/sdk:9.0
    depends_on:
      - postgres

  data-migration:
    image: ${REGISTRY:-kdvmanager}/data.migration:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/DataMigration/Dockerfile
      cache_from:
        - ${REGISTRY:-kdvmanager}/data.migration:${PLATFORM:-linux}-${TAG:-latest}
        - mcr.microsoft.com/dotnet/runtime:9.0
        - mcr.microsoft.com/dotnet/sdk:9.0
    depends_on:
      - postgres
      - crm-api
      - scheduling-api
