version: '3.4'

services:
  envoy:
    image: envoyproxy/envoy:v1.18.2
    restart: always

  postgres:
    image: postgres:latest

  scheduling-api:
    image: ${DOCKER_REGISTRY-}kdvmanagerservicesscheduling
    build:
      context: .
      dockerfile: Services/Scheduling/KDVManager.Services.Scheduling.Api/Dockerfile
    depends_on:
      - postgres

  childmanagement-api:
    image: ${DOCKER_REGISTRY-}kdvmanagerserviceschildmanagement
    build:
      context: .
      dockerfile: Services/ChildManagement/KDVManager.Services.ChildManagement.Api/Dockerfile
    depends_on:
      - postgres
