version: '3.4'

services:
  envoy:
    volumes:
      - ./Services/ApiGateways/Envoy/config:/etc/envoy
      - ./Services/ApiGateways/Envoy/logs:/var/log
    ports:
      - "5200:80"
      - "8001:8001"
      - "8080:8080"

  postgres:
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=sammy
      - POSTGRES_PASSWORD=shark
    volumes:
      - kdvmanager-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  web:
    image: ${REGISTRY:-kdvmanager}/web:${PLATFORM:-linux}-${TAG:-latest}
    ports:
      - "9090:80"

  crm-migrator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__KDVManagerCRMConnectionString=Server=postgres; port=5432; database=KDVManagerGroupManagementDB; User ID=sammy; password=shark; pooling=true
    depends_on:
      - postgres

  crm-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_Kestrel__Certificates__Default__Password=7g3xqiiedLGmDrvAXNy8
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__KDVManagerCRMConnectionString=Server=postgres; port=5432; database=KDVManagerGroupManagementDB; User ID=sammy; password=shark; pooling=true
    ports:
      - "7070:80"
      - "7079:443"
    volumes:
      - ${HOME}/.aspnet/https:/https/

  scheduling-migrator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__KDVManagerSchedulingConnectionString=Server=postgres; port=5432; database=KDVManagerSchedulingDB; User ID=sammy; password=shark; pooling=true
    depends_on:
      - postgres

  scheduling-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__KDVManagerSchedulingConnectionString=Server=postgres; port=5432; database=KDVManagerSchedulingDB; User ID=sammy; password=shark; pooling=true
    ports:
      - "80"
      - "443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

volumes:
  kdvmanager-data: null
