version: '3.4'

services:
  envoy:
    image: envoyproxy/envoy:v1.24.1

  postgres:
    image: postgres:latest

  crm-api:
    image: ${REGISTRY:-kdvmanager}/crm.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/CRM/Api/Dockerfile
    depends_on:
      - postgres

  crm-migrator:
    image: ${REGISTRY:-kdvmanager}/crm.migrator:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/CRM/Infrastructure/Dockerfile
    depends_on:
      - postgres

  scheduling-api:
    image: ${REGISTRY:-kdvmanager}/scheduling.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Scheduling/Api/Dockerfile
    depends_on:
      - postgres

  scheduling-migrator:
    image: ${REGISTRY:-kdvmanager}/scheduling.migrator:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Scheduling/Infrastructure/Dockerfile
    depends_on:
      - postgres
