version: '3.4'

services:
  envoy:
    volumes:
      - ./Services/ApiGateways/Envoy/config/envoy.yaml:/etc/envoy/envoy.yaml:ro
      - ./Services/ApiGateways/Envoy/logs:/var/log
    ports:
      - "5200:8080"
      - "8001:8001"

  postgres:
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=sammy
      - POSTGRES_PASSWORD=shark
    volumes:
      - kdvmanager-data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"

  rabbitmq:
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  web:
    image: ${REGISTRY:-kdvmanager}/web:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: ./web
      args:
        VITE_APP_AUTH0_DOMAIN: kdvmanager-development.eu.auth0.com
        VITE_APP_AUTH0_CLIENT_ID: 4pgRAIUb8feIsPVo53UwqMMzgN0jFFFq
        VITE_API_BASE_URL: //localhost:5200
    ports:
      - "9090:80"

  crm-migrator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__KDVManagerCRMConnectionString=Server=postgres; port=5432; database=KDVManagerCRMDB; User ID=sammy; password=shark; pooling=true
    depends_on:
      - postgres

  crm-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=7g3xqiiedLGmDrvAXNy8
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__KDVManagerCRMConnectionString=Server=postgres; port=5432; database=KDVManagerCRMDB; User ID=sammy; password=shark; pooling=true
      - ConnectionStrings__RabbitMQ=amqp://guest:guest@rabbitmq:5672/
    ports:
      - "80"
      - "443"
    volumes:
      - ${HOME}/.aspnet/https:/https/

  scheduling-migrator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__KDVManagerSchedulingConnectionString=Server=postgres; port=5432; database=KDVManagerSchedulingDB; User ID=sammy; password=shark; pooling=true
    depends_on:
      - postgres

  scheduling-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__KDVManagerSchedulingConnectionString=Server=postgres; port=5432; database=KDVManagerSchedulingDB; User ID=sammy; password=shark; pooling=true
      - ConnectionStrings__RabbitMQ=amqp://guest:guest@rabbitmq:5672/
    ports:
      - "80"
      - "443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  data-migration:
     environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__KDVManagerCRMConnectionString=Server=postgres; port=5432; database=KDVManagerCRMDB; User ID=sammy
      - ConnectionStrings__KDVManagerSchedulingConnectionString=Server=postgres; port=5432; database=KDVManagerSchedulingDB; User ID=sammy

volumes:
  kdvmanager-data: null
  rabbitmq-data: null
