version: '3.4'

services:
  postgres:
    image: postgres:latest

  groupmanagement.api:
    image: ${DOCKER_REGISTRY-}kdvmanagerservicesgroupmanagement
    build:
      context: .
      dockerfile: Services/GroupManagement/KDVManager.Services.GroupManagement.Api/Dockerfile
    depends_on:
      - postgres

  childmanagement.api:
    image: ${DOCKER_REGISTRY-}kdvmanagerserviceschildmanagement
    build:
      context: .
      dockerfile: Services/ChildManagement/KDVManager.Services.ChildManagement.Api/Dockerfile
    depends_on:
      - postgres
