/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { AdministratorListVM } from "../../models/administratorListVM";

import type { InviteAdministratorCommand } from "../../models/inviteAdministratorCommand";

import { executeFetch } from "../../../mutator/executeFetch";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getListAdministratorsUrl = () => {
  return `/crm/v1/administrators`;
};

export const listAdministrators = async (options?: RequestInit): Promise<AdministratorListVM[]> => {
  return executeFetch<AdministratorListVM[]>(getListAdministratorsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListAdministratorsQueryKey = () => {
  return [`/crm/v1/administrators`] as const;
};

export const getListAdministratorsQueryOptions = <
  TData = Awaited<ReturnType<typeof listAdministrators>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdministrators>>, TError, TData>>;
  request?: SecondParameter<typeof executeFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListAdministratorsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listAdministrators>>> = ({ signal }) =>
    listAdministrators({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listAdministrators>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListAdministratorsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listAdministrators>>
>;
export type ListAdministratorsQueryError = unknown;

export function useListAdministrators<
  TData = Awaited<ReturnType<typeof listAdministrators>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdministrators>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAdministrators>>,
          TError,
          Awaited<ReturnType<typeof listAdministrators>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListAdministrators<
  TData = Awaited<ReturnType<typeof listAdministrators>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listAdministrators>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAdministrators>>,
          TError,
          Awaited<ReturnType<typeof listAdministrators>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListAdministrators<
  TData = Awaited<ReturnType<typeof listAdministrators>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdministrators>>, TError, TData>>;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useListAdministrators<
  TData = Awaited<ReturnType<typeof listAdministrators>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdministrators>>, TError, TData>>;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListAdministratorsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getInviteAdministratorUrl = () => {
  return `/crm/v1/administrators/invitations`;
};

export const inviteAdministrator = async (
  inviteAdministratorCommand: InviteAdministratorCommand,
  options?: RequestInit,
): Promise<void> => {
  return executeFetch<void>(getInviteAdministratorUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(inviteAdministratorCommand),
  });
};

export const getInviteAdministratorMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof inviteAdministrator>>,
    TError,
    { data: InviteAdministratorCommand },
    TContext
  >;
  request?: SecondParameter<typeof executeFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof inviteAdministrator>>,
  TError,
  { data: InviteAdministratorCommand },
  TContext
> => {
  const mutationKey = ["inviteAdministrator"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof inviteAdministrator>>,
    { data: InviteAdministratorCommand }
  > = (props) => {
    const { data } = props ?? {};

    return inviteAdministrator(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type InviteAdministratorMutationResult = NonNullable<
  Awaited<ReturnType<typeof inviteAdministrator>>
>;
export type InviteAdministratorMutationBody = InviteAdministratorCommand;
export type InviteAdministratorMutationError = unknown;

export const useInviteAdministrator = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof inviteAdministrator>>,
      TError,
      { data: InviteAdministratorCommand },
      TContext
    >;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof inviteAdministrator>>,
  TError,
  { data: InviteAdministratorCommand },
  TContext
> => {
  return useMutation(getInviteAdministratorMutationOptions(options), queryClient);
};

export const getDeleteAdministratorUrl = (userId: string) => {
  return `/crm/v1/administrators/${userId}`;
};

export const deleteAdministrator = async (
  userId: string,
  options?: RequestInit,
): Promise<void> => {
  return executeFetch<void>(getDeleteAdministratorUrl(userId), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteAdministratorMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteAdministrator>>,
    TError,
    { userId: string },
    TContext
  >;
  request?: SecondParameter<typeof executeFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteAdministrator>>,
  TError,
  { userId: string },
  TContext
> => {
  const mutationKey = ["deleteAdministrator"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteAdministrator>>,
    { userId: string }
  > = (props) => {
    const { userId } = props ?? {};

    return deleteAdministrator(userId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteAdministratorMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteAdministrator>>
>;
export type DeleteAdministratorMutationError = unknown;

export const useDeleteAdministrator = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteAdministrator>>,
      TError,
      { userId: string },
      TContext
    >;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteAdministrator>>,
  TError,
  { userId: string },
  TContext
> => {
  return useMutation(getDeleteAdministratorMutationOptions(options), queryClient);
};

export const getRevokeInvitationUrl = (invitationId: string) => {
  return `/crm/v1/administrators/invitations/${invitationId}`;
};

export const revokeInvitation = async (
  invitationId: string,
  options?: RequestInit,
): Promise<void> => {
  return executeFetch<void>(getRevokeInvitationUrl(invitationId), {
    ...options,
    method: "DELETE",
  });
};

export const getRevokeInvitationMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof revokeInvitation>>,
    TError,
    { invitationId: string },
    TContext
  >;
  request?: SecondParameter<typeof executeFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof revokeInvitation>>,
  TError,
  { invitationId: string },
  TContext
> => {
  const mutationKey = ["revokeInvitation"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof revokeInvitation>>,
    { invitationId: string }
  > = (props) => {
    const { invitationId } = props ?? {};

    return revokeInvitation(invitationId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RevokeInvitationMutationResult = NonNullable<
  Awaited<ReturnType<typeof revokeInvitation>>
>;
export type RevokeInvitationMutationError = unknown;

export const useRevokeInvitation = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof revokeInvitation>>,
      TError,
      { invitationId: string },
      TContext
    >;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof revokeInvitation>>,
  TError,
  { invitationId: string },
  TContext
> => {
  return useMutation(getRevokeInvitationMutationOptions(options), queryClient);
};
