/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * KDVManager CRM API
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { AdministratorListVM } from "../../models/administratorListVM";

import type { CreateAdministratorCommand } from "../../models/createAdministratorCommand";

import type { ListAdministratorsParams } from "../../models/listAdministratorsParams";

import { executeFetch } from "../../../mutator/executeFetch";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getListAdministratorsUrl = (params: ListAdministratorsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/crm/v1/administrators?${stringifiedParams}`
    : `/crm/v1/administrators`;
};

export const listAdministrators = async (
  params: ListAdministratorsParams,
  options?: RequestInit,
): Promise<AdministratorListVM[]> => {
  return executeFetch<AdministratorListVM[]>(getListAdministratorsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListAdministratorsQueryKey = (params?: ListAdministratorsParams) => {
  return [`/crm/v1/administrators`, ...(params ? [params] : [])] as const;
};

export const getListAdministratorsQueryOptions = <
  TData = Awaited<ReturnType<typeof listAdministrators>>,
  TError = unknown,
>(
  params: ListAdministratorsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdministrators>>, TError, TData>>;
    request?: SecondParameter<typeof executeFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListAdministratorsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listAdministrators>>> = ({ signal }) =>
    listAdministrators(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listAdministrators>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListAdministratorsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listAdministrators>>
>;
export type ListAdministratorsQueryError = unknown;

export function useListAdministrators<
  TData = Awaited<ReturnType<typeof listAdministrators>>,
  TError = unknown,
>(
  params: ListAdministratorsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdministrators>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAdministrators>>,
          TError,
          Awaited<ReturnType<typeof listAdministrators>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListAdministrators<
  TData = Awaited<ReturnType<typeof listAdministrators>>,
  TError = unknown,
>(
  params: ListAdministratorsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listAdministrators>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAdministrators>>,
          TError,
          Awaited<ReturnType<typeof listAdministrators>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListAdministrators<
  TData = Awaited<ReturnType<typeof listAdministrators>>,
  TError = unknown,
>(
  params: ListAdministratorsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdministrators>>, TError, TData>>;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useListAdministrators<
  TData = Awaited<ReturnType<typeof listAdministrators>>,
  TError = unknown,
>(
  params: ListAdministratorsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listAdministrators>>, TError, TData>>;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListAdministratorsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getCreateAdministratorUrl = () => {
  return `/crm/v1/administrators`;
};

export const createAdministrator = async (
  createAdministratorCommand: CreateAdministratorCommand,
  options?: RequestInit,
): Promise<string> => {
  return executeFetch<string>(getCreateAdministratorUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createAdministratorCommand),
  });
};

export const getCreateAdministratorMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createAdministrator>>,
    TError,
    { data: CreateAdministratorCommand },
    TContext
  >;
  request?: SecondParameter<typeof executeFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createAdministrator>>,
  TError,
  { data: CreateAdministratorCommand },
  TContext
> => {
  const mutationKey = ["createAdministrator"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createAdministrator>>,
    { data: CreateAdministratorCommand }
  > = (props) => {
    const { data } = props ?? {};

    return createAdministrator(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateAdministratorMutationResult = NonNullable<
  Awaited<ReturnType<typeof createAdministrator>>
>;
export type CreateAdministratorMutationBody = CreateAdministratorCommand;
export type CreateAdministratorMutationError = unknown;

export const useCreateAdministrator = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createAdministrator>>,
      TError,
      { data: CreateAdministratorCommand },
      TContext
    >;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createAdministrator>>,
  TError,
  { data: CreateAdministratorCommand },
  TContext
> => {
  return useMutation(getCreateAdministratorMutationOptions(options), queryClient);
};
export const getDeleteAdministratorUrl = (id: string) => {
  return `/crm/v1/administrators/${id}`;
};

export const deleteAdministrator = async (id: string, options?: RequestInit): Promise<void> => {
  return executeFetch<void>(getDeleteAdministratorUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteAdministratorMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteAdministrator>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof executeFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteAdministrator>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteAdministrator"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteAdministrator>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteAdministrator(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteAdministratorMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteAdministrator>>
>;

export type DeleteAdministratorMutationError = unknown;

export const useDeleteAdministrator = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteAdministrator>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteAdministrator>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteAdministratorMutationOptions(options), queryClient);
};
