apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-migration-cronjob
spec:
  # Run every day at 2:00 AM UTC
  schedule: "0 2 * * *"
  timeZone: "UTC"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      ttlSecondsAfterFinished: 86400  # Clean up jobs after 24 hours
      template:
        metadata:
          labels:
            app: data-migration
            release: production
        spec:
          restartPolicy: Never
          serviceAccountName: kdvmanager-sa
          containers:
          - name: data-migration
            image: ghcr.io/luuklabs/kdvmanager/data.migration:linux-main
            imagePullPolicy: Always
            # Run full migration by default, you can change this to specific migration types
            # args: ["--children-only"]  # Uncomment for children-only migration
            # args: ["--scheduling-only"]  # Uncomment for scheduling-only migration
            env:
            - name: POSTGRES_SERVER
              value: "private-db-kdvmanager-ams3-do-user-13194146-0.l.db.ondigitalocean.com"
            - name: POSTGRES_USER
              value: "doadmin"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kdvmanager-postgres-secret
                  key: password
            - name: POSTGRES_PORT
              value: "25060"
            - name: CRM_POSTGRES_DATABASE
              value: "KDVManagerCRMDB"
            - name: SCHEDULING_POSTGRES_DATABASE
              value: "KDVManagerSchedulingDB"
            - name: ConnectionStrings__KDVManagerCRMConnectionString
              value: "Server=$(POSTGRES_SERVER); port=$(POSTGRES_PORT); database=$(CRM_POSTGRES_DATABASE); User ID=$(POSTGRES_USER); password=$(POSTGRES_PASSWORD); pooling=true; sslmode=require"
            - name: ConnectionStrings__KDVManagerSchedulingConnectionString
              value: "Server=$(POSTGRES_SERVER); port=$(POSTGRES_PORT); database=$(SCHEDULING_POSTGRES_DATABASE); User ID=$(POSTGRES_USER); password=$(POSTGRES_PASSWORD); pooling=true; sslmode=require"
            - name: ConnectionStrings__MSSQLSourceConnectionString
              valueFrom:
                secretKeyRef:
                  name: mssql-source-secret
                  key: connectionString
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            resources:
              limits:
                memory: 256Mi
                cpu: 400m
              requests:
                memory: 128Mi
                cpu: 200m
          imagePullSecrets:
          - name: ghcr-secret
