apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduling-api
  labels:
    app: scheduling-api
    release: production
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0 
  selector:
    matchLabels:
      app: scheduling-api
      release: production
  template:
    metadata:
      labels:
        app: scheduling-api
        release: production
    spec:
      containers:
      - name: scheduling-pod
        image: ghcr.io/luukvh/kdvmanager/scheduling.api:linux-master
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
          - name: https
            containerPort: 443
            protocol: TCP
        env:
          - name: ASPNETCORE_URLS
            value: "http://+:80"
          - name: POSTGRES_SERVER
            value: "postgres"
          - name: POSTGRES_USER
            value: "admin"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                  name: kdvmanager-postgres-secret
                  key: superUserPassword        
          - name: ConnectionStrings__KDVManagerSchedulingConnectionString
            value: "Server=$(POSTGRES_SERVER); port=5432; database=KDVManagerSchedulingDB; User ID=$(POSTGRES_USER); password=$(POSTGRES_PASSWORD); pooling = true"
      initContainers:
      - name: scheduling-migration
        image: ghcr.io/luukvh/kdvmanager/scheduling.migrator:linux-master
        imagePullPolicy: Always
        env:
          - name: POSTGRES_SERVER
            value: "postgres"
          - name: POSTGRES_USER
            value: "admin"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                  name: kdvmanager-postgres-secret
                  key: superUserPassword        
          - name: ConnectionStrings__KDVManagerSchedulingConnectionString
            value: "Server=$(POSTGRES_SERVER); port=5432; database=KDVManagerSchedulingDB; User ID=$(POSTGRES_USER); password=$(POSTGRES_PASSWORD); pooling = true"