apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduling-api
  labels:
    app: scheduling-api
    release: production
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0 
  selector:
    matchLabels:
      app: scheduling-api
      release: production
  template:
    metadata:
      labels:
        app: scheduling-api
        release: production
    spec:
      serviceAccountName: kdvmanager-sa
      containers:
      - name: scheduling-pod
        image: ghcr.io/luuklabs/kdvmanager/scheduling.api:linux-main
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            port: 80
            path: /healthz
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            port: 80
            path: /healthz
          initialDelaySeconds: 10
          periodSeconds: 3
        resources:
          limits:
            memory: 100Mi
            cpu: 500m
          requests:
            memory: 50Mi
            cpu: 200m
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
          - name: https
            containerPort: 443
            protocol: TCP
        env:
          - name: ASPNETCORE_URLS
            value: "http://+:80"
          - name: POSTGRES_SERVER
            value: "private-db-kdvmanager-ams3-do-user-13194146-0.l.db.ondigitalocean.com"
          - name: POSTGRES_USER
            value: "doadmin"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kdvmanager-postgres-secret
                key: password
          - name: POSTGRES_PORT
            value: "25060"
          - name: POSTGRES_DATABASE
            value: "KDVManagerSchedulingDB"
          - name: ConnectionStrings__KDVManagerSchedulingConnectionString
            value: "Server=$(POSTGRES_SERVER); port=$(POSTGRES_PORT); database=$(POSTGRES_DATABASE); User ID=$(POSTGRES_USER); password=$(POSTGRES_PASSWORD); pooling=true; sslmode=require"
      initContainers:
      - name: scheduling-migration
        image: ghcr.io/luuklabs/kdvmanager/scheduling.migrator:linux-main
        imagePullPolicy: Always
        env:
          - name: POSTGRES_SERVER
            value: "private-db-kdvmanager-ams3-do-user-13194146-0.l.db.ondigitalocean.com"
          - name: POSTGRES_USER
            value: "doadmin"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kdvmanager-postgres-secret
                key: password
          - name: POSTGRES_PORT
            value: "25060"
          - name: POSTGRES_DATABASE
            value: "KDVManagerSchedulingDB"
          - name: ConnectionStrings__KDVManagerSchedulingConnectionString
            value: "Server=$(POSTGRES_SERVER); port=$(POSTGRES_PORT); database=$(POSTGRES_DATABASE); User ID=$(POSTGRES_USER); password=$(POSTGRES_PASSWORD); pooling=true; sslmode=require"