apiVersion: v1
kind: Service
metadata:
  name: scheduling-api
  namespace: kdvmanager-prod
  labels:
    app: scheduling-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: scheduling-api
    release: production
