name: crm-api

on:
  workflow_dispatch:
  push:
    branches:
    - main
  
  pull_request:
    branches:
    - main

    paths:
    - src/Services/CRM/**
    - .github/workflows/crm-api.yml
env:
  SERVICE: crm-api
  IMAGE: crm-api

jobs:

  BuildContainersForPR_Linux:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: ./.github/workflows/composite/build
      with:
        service: ${{ env.SERVICE }}
        registry_endpoint: ${{ vars.REGISTRY_ENDPOINT }}

  BuildLinux:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: ./.github/workflows/composite/build-push
      with:
        service: ${{ env.SERVICE }}
        registry_host: ${{ vars.REGISTRY_HOST }}
        registry_endpoint: ${{ vars.REGISTRY_ENDPOINT }}
        image_name: ${{ env.IMAGE }}
        registry_username: ${{ vars.REGISTRY_USERNAME }}
        registry_password: ${{ secrets.REGISTRY_PASSWORD }}