name: web

on:
  workflow_dispatch:
  push:
    branches:
    - main
  
  pull_request:
    branches:
    - main

    paths:
    - src/web/**
    - .github/workflows/web.yml
env:
  REGISTRY: ghcr.io
  SERVICE: web
  IMAGE: web

jobs:

  CI:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ./src/web

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0 

    - uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '24.x'
        cache: 'pnpm'
        cache-dependency-path: src/web/pnpm-lock.yaml

    - name: Install pnpm dependencies
      run: pnpm install --frozen-lockfile

    - name: Run ESLint
      run: pnpm eslint
    
    - name: Run typecheck
      run: pnpm tsc -b

  BuildContainersForPR_Linux:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: ${{ github.event_name == 'pull_request' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - uses: ./.github/workflows/composite/build
      with:
        service: ${{ env.SERVICE }}
        registry_endpoint: ${{ vars.REGISTRY_ENDPOINT }}

  BuildLinux:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: ${{ github.event_name != 'pull_request' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - uses: ./.github/workflows/composite/build-push
      with:
        service: ${{ env.SERVICE }}
        registry_host: ${{ env.REGISTRY }}
        registry_endpoint: ${{ vars.REGISTRY_ENDPOINT }}
        image_name: ${{ env.IMAGE }}
        registry_username: ${{ github.actor }}
        registry_password: ${{ secrets.GITHUB_TOKEN }}
