/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * KDVManager Tenants API
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { AddTenantCommand } from "../../models/addTenantCommand";

import type { ListTenantsParams } from "../../models/listTenantsParams";

import type { TenantDetailVM } from "../../models/tenantDetailVM";

import type { TenantListVM } from "../../models/tenantListVM";

import type { UnprocessableEntityResponse } from "../../models/unprocessableEntityResponse";

import type { UpdateTenantCommand } from "../../models/updateTenantCommand";

import { executeFetchPaginated } from "../../../mutator/executeFetchPaginated";
import { executeFetch } from "../../../mutator/executeFetch";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getListTenantsUrl = (params?: ListTenantsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/tenants/v1/tenants?${stringifiedParams}`
    : `/tenants/v1/tenants`;
};

export const listTenants = async (
  params?: ListTenantsParams,
  options?: RequestInit,
): Promise<TenantListVM[]> => {
  return executeFetchPaginated<TenantListVM[]>(getListTenantsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListTenantsQueryKey = (params?: ListTenantsParams) => {
  return [`/tenants/v1/tenants`, ...(params ? [params] : [])] as const;
};

export const getListTenantsQueryOptions = <
  TData = Awaited<ReturnType<typeof listTenants>>,
  TError = unknown,
>(
  params?: ListTenantsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listTenants>>, TError, TData>>;
    request?: SecondParameter<typeof executeFetchPaginated>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListTenantsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listTenants>>> = ({ signal }) =>
    listTenants(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listTenants>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListTenantsQueryResult = NonNullable<Awaited<ReturnType<typeof listTenants>>>;
export type ListTenantsQueryError = unknown;

export function useListTenants<TData = Awaited<ReturnType<typeof listTenants>>, TError = unknown>(
  params: undefined | ListTenantsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listTenants>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTenants>>,
          TError,
          Awaited<ReturnType<typeof listTenants>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof executeFetchPaginated>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListTenants<TData = Awaited<ReturnType<typeof listTenants>>, TError = unknown>(
  params?: ListTenantsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listTenants>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTenants>>,
          TError,
          Awaited<ReturnType<typeof listTenants>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof executeFetchPaginated>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListTenants<TData = Awaited<ReturnType<typeof listTenants>>, TError = unknown>(
  params?: ListTenantsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listTenants>>, TError, TData>>;
    request?: SecondParameter<typeof executeFetchPaginated>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useListTenants<TData = Awaited<ReturnType<typeof listTenants>>, TError = unknown>(
  params?: ListTenantsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listTenants>>, TError, TData>>;
    request?: SecondParameter<typeof executeFetchPaginated>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListTenantsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetTenantByIdUrl = (id: string) => {
  return `/tenants/v1/tenants/${id}`;
};

export const getTenantById = async (
  id: string,
  options?: RequestInit,
): Promise<TenantDetailVM> => {
  return executeFetch<TenantDetailVM>(getGetTenantByIdUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetTenantByIdQueryKey = (id: string) => {
  return [`/tenants/v1/tenants/${id}`] as const;
};

export const getGetTenantByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getTenantById>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTenantById>>, TError, TData>>;
    request?: SecondParameter<typeof executeFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTenantByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTenantById>>> = ({ signal }) =>
    getTenantById(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getTenantById>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetTenantByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getTenantById>>>;
export type GetTenantByIdQueryError = unknown;

export function useGetTenantById<
  TData = Awaited<ReturnType<typeof getTenantById>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTenantById>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTenantById>>,
          TError,
          Awaited<ReturnType<typeof getTenantById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetTenantById<
  TData = Awaited<ReturnType<typeof getTenantById>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTenantById>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTenantById>>,
          TError,
          Awaited<ReturnType<typeof getTenantById>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetTenantById<
  TData = Awaited<ReturnType<typeof getTenantById>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTenantById>>, TError, TData>>;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetTenantById<
  TData = Awaited<ReturnType<typeof getTenantById>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTenantById>>, TError, TData>>;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetTenantByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getAddTenantUrl = () => {
  return `/tenants/v1/tenants`;
};

export const addTenant = async (
  addTenantCommand?: AddTenantCommand,
  options?: RequestInit,
): Promise<string> => {
  return executeFetch<string>(getAddTenantUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(addTenantCommand),
  });
};

export const getAddTenantMutationOptions = <
  TError = UnprocessableEntityResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addTenant>>,
    TError,
    { data?: AddTenantCommand },
    TContext
  >;
  request?: SecondParameter<typeof executeFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addTenant>>,
  TError,
  { data?: AddTenantCommand },
  TContext
> => {
  const mutationKey = ["addTenant"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addTenant>>,
    { data?: AddTenantCommand }
  > = (props) => {
    const { data } = props ?? {};

    return addTenant(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddTenantMutationResult = NonNullable<Awaited<ReturnType<typeof addTenant>>>;
export type AddTenantMutationBody = AddTenantCommand | undefined;
export type AddTenantMutationError = UnprocessableEntityResponse;

export const useAddTenant = <TError = UnprocessableEntityResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addTenant>>,
      TError,
      { data?: AddTenantCommand },
      TContext
    >;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof addTenant>>,
  TError,
  { data?: AddTenantCommand },
  TContext
> => {
  return useMutation(getAddTenantMutationOptions(options), queryClient);
};

export const getUpdateTenantUrl = (id: string) => {
  return `/tenants/v1/tenants/${id}`;
};

export const updateTenant = async (
  id: string,
  updateTenantCommand: UpdateTenantCommand,
  options?: RequestInit,
): Promise<void> => {
  return executeFetch<void>(getUpdateTenantUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateTenantCommand),
  });
};

export const getUpdateTenantMutationOptions = <
  TError = UnprocessableEntityResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateTenant>>,
    TError,
    { id: string; data: UpdateTenantCommand },
    TContext
  >;
  request?: SecondParameter<typeof executeFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateTenant>>,
  TError,
  { id: string; data: UpdateTenantCommand },
  TContext
> => {
  const mutationKey = ["updateTenant"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateTenant>>,
    { id: string; data: UpdateTenantCommand }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateTenant(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateTenantMutationResult = NonNullable<Awaited<ReturnType<typeof updateTenant>>>;
export type UpdateTenantMutationBody = UpdateTenantCommand;
export type UpdateTenantMutationError = UnprocessableEntityResponse;

export const useUpdateTenant = <TError = UnprocessableEntityResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateTenant>>,
      TError,
      { id: string; data: UpdateTenantCommand },
      TContext
    >;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateTenant>>,
  TError,
  { id: string; data: UpdateTenantCommand },
  TContext
> => {
  return useMutation(getUpdateTenantMutationOptions(options), queryClient);
};

export const getActivateTenantUrl = (id: string) => {
  return `/tenants/v1/tenants/${id}/activate`;
};

export const activateTenant = async (id: string, options?: RequestInit): Promise<void> => {
  return executeFetch<void>(getActivateTenantUrl(id), {
    ...options,
    method: "POST",
  });
};

export const getActivateTenantMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof activateTenant>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof executeFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof activateTenant>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["activateTenant"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof activateTenant>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return activateTenant(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ActivateTenantMutationResult = NonNullable<
  Awaited<ReturnType<typeof activateTenant>>
>;

export type ActivateTenantMutationError = unknown;

export const useActivateTenant = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof activateTenant>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof activateTenant>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getActivateTenantMutationOptions(options), queryClient);
};

export const getDeactivateTenantUrl = (id: string) => {
  return `/tenants/v1/tenants/${id}/deactivate`;
};

export const deactivateTenant = async (id: string, options?: RequestInit): Promise<void> => {
  return executeFetch<void>(getDeactivateTenantUrl(id), {
    ...options,
    method: "POST",
  });
};

export const getDeactivateTenantMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deactivateTenant>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof executeFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deactivateTenant>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deactivateTenant"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deactivateTenant>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deactivateTenant(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeactivateTenantMutationResult = NonNullable<
  Awaited<ReturnType<typeof deactivateTenant>>
>;

export type DeactivateTenantMutationError = unknown;

export const useDeactivateTenant = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deactivateTenant>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deactivateTenant>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeactivateTenantMutationOptions(options), queryClient);
};
