/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * KDVManager Scheduling API
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { AbsenceListByChildIdVM } from "../../models/absenceListByChildIdVM";

import type { AddAbsenceCommand } from "../../models/addAbsenceCommand";

import type { ProblemDetails } from "../../models/problemDetails";

import type { UnprocessableEntityResponse } from "../../models/unprocessableEntityResponse";

import { executeFetch } from "../../../mutator/executeFetch";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getGetAbsencesByChildIdUrl = (childId: string) => {
  return `/scheduling/v1/children/${childId}/absences`;
};

export const getAbsencesByChildId = async (
  childId: string,
  options?: RequestInit,
): Promise<AbsenceListByChildIdVM[]> => {
  return executeFetch<AbsenceListByChildIdVM[]>(getGetAbsencesByChildIdUrl(childId), {
    ...options,
    method: "GET",
  });
};

export const getGetAbsencesByChildIdQueryKey = (childId: string) => {
  return [`/scheduling/v1/children/${childId}/absences`] as const;
};

export const getGetAbsencesByChildIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getAbsencesByChildId>>,
  TError = unknown,
>(
  childId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAbsencesByChildId>>, TError, TData>
    >;
    request?: SecondParameter<typeof executeFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAbsencesByChildIdQueryKey(childId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAbsencesByChildId>>> = ({ signal }) =>
    getAbsencesByChildId(childId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: childId !== null && childId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getAbsencesByChildId>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetAbsencesByChildIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAbsencesByChildId>>
>;
export type GetAbsencesByChildIdQueryError = unknown;

export function useGetAbsencesByChildId<
  TData = Awaited<ReturnType<typeof getAbsencesByChildId>>,
  TError = unknown,
>(
  childId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAbsencesByChildId>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAbsencesByChildId>>,
          TError,
          Awaited<ReturnType<typeof getAbsencesByChildId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAbsencesByChildId<
  TData = Awaited<ReturnType<typeof getAbsencesByChildId>>,
  TError = unknown,
>(
  childId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAbsencesByChildId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAbsencesByChildId>>,
          TError,
          Awaited<ReturnType<typeof getAbsencesByChildId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAbsencesByChildId<
  TData = Awaited<ReturnType<typeof getAbsencesByChildId>>,
  TError = unknown,
>(
  childId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAbsencesByChildId>>, TError, TData>
    >;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetAbsencesByChildId<
  TData = Awaited<ReturnType<typeof getAbsencesByChildId>>,
  TError = unknown,
>(
  childId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAbsencesByChildId>>, TError, TData>
    >;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAbsencesByChildIdQueryOptions(childId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getAddAbsenceUrl = (childId: string) => {
  return `/scheduling/v1/children/${childId}/absences`;
};

export const addAbsence = async (
  childId: string,
  addAbsenceCommand?: AddAbsenceCommand,
  options?: RequestInit,
): Promise<string> => {
  return executeFetch<string>(getAddAbsenceUrl(childId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(addAbsenceCommand),
  });
};

export const getAddAbsenceMutationOptions = <
  TError = UnprocessableEntityResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addAbsence>>,
    TError,
    { childId: string; data?: AddAbsenceCommand },
    TContext
  >;
  request?: SecondParameter<typeof executeFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addAbsence>>,
  TError,
  { childId: string; data?: AddAbsenceCommand },
  TContext
> => {
  const mutationKey = ["addAbsence"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addAbsence>>,
    { childId: string; data?: AddAbsenceCommand }
  > = (props) => {
    const { childId, data } = props ?? {};

    return addAbsence(childId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddAbsenceMutationResult = NonNullable<Awaited<ReturnType<typeof addAbsence>>>;
export type AddAbsenceMutationBody = AddAbsenceCommand | undefined;
export type AddAbsenceMutationError = UnprocessableEntityResponse;

export const useAddAbsence = <TError = UnprocessableEntityResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addAbsence>>,
      TError,
      { childId: string; data?: AddAbsenceCommand },
      TContext
    >;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof addAbsence>>,
  TError,
  { childId: string; data?: AddAbsenceCommand },
  TContext
> => {
  return useMutation(getAddAbsenceMutationOptions(options), queryClient);
};
export const getDeleteAbsenceUrl = (id: string) => {
  return `/scheduling/v1/absences/${id}`;
};

export const deleteAbsence = async (id: string, options?: RequestInit): Promise<void> => {
  return executeFetch<void>(getDeleteAbsenceUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteAbsenceMutationOptions = <
  TError = ProblemDetails,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteAbsence>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof executeFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteAbsence>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteAbsence"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAbsence>>, { id: string }> = (
    props,
  ) => {
    const { id } = props ?? {};

    return deleteAbsence(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteAbsenceMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAbsence>>>;

export type DeleteAbsenceMutationError = ProblemDetails;

export const useDeleteAbsence = <TError = ProblemDetails, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteAbsence>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof executeFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteAbsence>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteAbsenceMutationOptions(options), queryClient);
};
